import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * Interpolation write-through (Rebuild Phase 4 / requirement B5).
 *
 * Interpolated contours are written through (auto-accepted) the moment they're
 * generated — no promote-before-save gate, no `autoAcceptInterpolated` preference.
 * These tests pin: (1) `acceptAllAutoGenerated` promotes every auto-generated
 * contour (registers its UID + clears the `autoGenerated` flag) and skips
 * already-accepted ones; (2) the `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED`
 * handler accepts UNCONDITIONALLY — there is no preference consulted.
 */
const m = vi.hoisted(() => ({
  listeners: new Map<string, EventListener>(),
  getAllAnnotations: vi.fn((): unknown[] => []),
  getAnnotation: vi.fn((_uid?: string): unknown => undefined),
  addAnnotation: vi.fn((): boolean => true),
}));

const EV_INTERP = 'ANNOTATION_INTERPOLATION_PROCESS_COMPLETED';
const EV_SELECT = 'ANNOTATION_SELECTION_CHANGE';

vi.mock('@cornerstonejs/core', () => ({
  eventTarget: {
    addEventListener: (type: string, cb: EventListener) => m.listeners.set(type, cb),
    removeEventListener: (type: string) => m.listeners.delete(type),
  },
}));
vi.mock('@cornerstonejs/tools', () => ({
  annotation: { state: { getAllAnnotations: m.getAllAnnotations, getAnnotation: m.getAnnotation } },
  // Literals inlined — the factory is hoisted above the const declarations below.
  Enums: { Events: { ANNOTATION_INTERPOLATION_PROCESS_COMPLETED: 'ANNOTATION_INTERPOLATION_PROCESS_COMPLETED', ANNOTATION_SELECTION_CHANGE: 'ANNOTATION_SELECTION_CHANGE' } },
}));
vi.mock('../contourRepresentation', () => ({ addAnnotation: m.addAnnotation }));

import {
  acceptAllAutoGenerated,
  acceptAnnotation,
  initialize,
  dispose,
} from '../interpolationAcceptance';

beforeEach(() => {
  m.listeners.clear();
  m.getAllAnnotations.mockReset().mockReturnValue([]);
  m.addAnnotation.mockReset().mockReturnValue(true);
});
afterEach(() => dispose());

describe('interpolation write-through (B5)', () => {
  it('acceptAnnotation promotes an auto-generated contour and is a no-op on an accepted one', () => {
    const auto = { autoGenerated: true };
    expect(acceptAnnotation(auto)).toBe(true);
    expect(auto.autoGenerated).toBe(false); // flipped → solid render
    expect(m.addAnnotation).toHaveBeenCalledTimes(1);

    m.addAnnotation.mockClear();
    expect(acceptAnnotation({ autoGenerated: false })).toBe(false); // already accepted
    expect(m.addAnnotation).not.toHaveBeenCalled();
  });

  it('acceptAllAutoGenerated promotes every auto-generated contour, skipping accepted ones', () => {
    const a = { autoGenerated: true };
    const b = { autoGenerated: false };
    const c = { autoGenerated: true };
    m.getAllAnnotations.mockReturnValue([a, b, c]);

    expect(acceptAllAutoGenerated()).toBe(2);
    expect(a.autoGenerated).toBe(false);
    expect(c.autoGenerated).toBe(false);
    expect(b.autoGenerated).toBe(false); // untouched (was already accepted)
    expect(m.addAnnotation).toHaveBeenCalledTimes(2);
  });

  it('the interpolation-completed event writes through UNCONDITIONALLY (no preference gate)', () => {
    const auto = { autoGenerated: true };
    m.getAllAnnotations.mockReturnValue([auto]);

    initialize();
    const handler = m.listeners.get(EV_INTERP);
    expect(handler, 'interpolation-completed handler must be registered').toBeDefined();

    handler!(new Event(EV_INTERP));
    // No preferencesStore is consulted — the contour is promoted purely from the event.
    expect(auto.autoGenerated).toBe(false);
    expect(m.addAnnotation).toHaveBeenCalledTimes(1);
  });
});
