import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * Interpolation write-through (Rebuild Phase 4 / requirement B5).
 *
 * Interpolated contours are written through (auto-accepted) the moment they're
 * generated — no promote-before-save gate, no `autoAcceptInterpolated` preference.
 * These tests pin: (1) `acceptAllAutoGenerated` promotes every auto-generated
 * contour (registers its UID + clears the `autoGenerated` flag) and skips
 * already-accepted ones; (2) the `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED`
 * handler accepts UNCONDITIONALLY — there is no preference consulted.
 */
const m = vi.hoisted(() => ({
  listeners: new Map<string, EventListener>(),
  getAllAnnotations: vi.fn((): unknown[] => []),
  getAnnotation: vi.fn((_uid?: string): unknown => undefined),
  addAnnotation: vi.fn((): boolean => true),
}));

const EV_INTERP = 'ANNOTATION_INTERPOLATION_PROCESS_COMPLETED';
const EV_SELECT = 'ANNOTATION_SELECTION_CHANGE';
const EV_MODIFIED = 'ANNOTATION_MODIFIED';

vi.mock('@cornerstonejs/core', () => ({
  eventTarget: {
    addEventListener: (type: string, cb: EventListener) => m.listeners.set(type, cb),
    removeEventListener: (type: string) => m.listeners.delete(type),
  },
}));
vi.mock('@cornerstonejs/tools', () => ({
  annotation: { state: { getAllAnnotations: m.getAllAnnotations, getAnnotation: m.getAnnotation } },
  // Literals inlined — the factory is hoisted above the const declarations below.
  Enums: { Events: { ANNOTATION_INTERPOLATION_PROCESS_COMPLETED: 'ANNOTATION_INTERPOLATION_PROCESS_COMPLETED', ANNOTATION_SELECTION_CHANGE: 'ANNOTATION_SELECTION_CHANGE', ANNOTATION_MODIFIED: 'ANNOTATION_MODIFIED' } },
}));
vi.mock('../contourRepresentation', () => ({ addAnnotation: m.addAnnotation }));

import {
  acceptAllAutoGenerated,
  acceptAnnotation,
  segmentProvenance,
  clearContourProvenance,
  initialize,
  dispose,
} from '../interpolationAcceptance';

beforeEach(() => {
  m.listeners.clear();
  m.getAllAnnotations.mockReset().mockReturnValue([]);
  m.addAnnotation.mockReset().mockReturnValue(true);
});
afterEach(() => dispose());

describe('interpolation write-through (B5)', () => {
  it('acceptAnnotation promotes an auto-generated contour and is a no-op on an accepted one', () => {
    const auto = { autoGenerated: true };
    expect(acceptAnnotation(auto)).toBe(true);
    expect(auto.autoGenerated).toBe(false); // flipped → solid render
    expect(m.addAnnotation).toHaveBeenCalledTimes(1);

    m.addAnnotation.mockClear();
    expect(acceptAnnotation({ autoGenerated: false })).toBe(false); // already accepted
    expect(m.addAnnotation).not.toHaveBeenCalled();
  });

  it('acceptAllAutoGenerated promotes every auto-generated contour, skipping accepted ones', () => {
    const a = { autoGenerated: true };
    const b = { autoGenerated: false };
    const c = { autoGenerated: true };
    m.getAllAnnotations.mockReturnValue([a, b, c]);

    expect(acceptAllAutoGenerated()).toBe(2);
    expect(a.autoGenerated).toBe(false);
    expect(c.autoGenerated).toBe(false);
    expect(b.autoGenerated).toBe(false); // untouched (was already accepted)
    expect(m.addAnnotation).toHaveBeenCalledTimes(2);
  });

  it('the interpolation-completed event writes through UNCONDITIONALLY (no preference gate)', () => {
    const auto = { autoGenerated: true };
    m.getAllAnnotations.mockReturnValue([auto]);

    initialize();
    const handler = m.listeners.get(EV_INTERP);
    expect(handler, 'interpolation-completed handler must be registered').toBeDefined();

    handler!(new Event(EV_INTERP));
    // No preferencesStore is consulted — the contour is promoted purely from the event.
    expect(auto.autoGenerated).toBe(false);
    expect(m.addAnnotation).toHaveBeenCalledTimes(1);
  });
});

describe('contour provenance (signal 22)', () => {
  it('acceptAnnotation stamps a PERSISTENT interpolated provenance (survives autoGenerated clearing)', () => {
    const auto: { autoGenerated: boolean; metadata?: Record<string, unknown> } = { autoGenerated: true };
    expect(acceptAnnotation(auto)).toBe(true);
    expect(auto.autoGenerated).toBe(false); // transient flag cleared…
    expect(auto.metadata?.provenance).toBe('interpolated'); // …but provenance persists
  });

  it('segmentProvenance returns interpolated only for the matching segment with a stamped contour', () => {
    m.getAllAnnotations.mockReturnValue([
      { data: { segmentation: { segmentationId: 'seg-A', segmentIndex: 1 } }, metadata: { provenance: 'interpolated' } },
      { data: { segmentation: { segmentationId: 'seg-A', segmentIndex: 2 } }, metadata: { provenance: 'manual' } },
      { data: { segmentation: { segmentationId: 'seg-B', segmentIndex: 1 } }, metadata: {} },
    ]);
    expect(segmentProvenance('seg-A', 1)).toBe('interpolated');
    expect(segmentProvenance('seg-A', 2)).toBeUndefined(); // manual → no badge
    expect(segmentProvenance('seg-B', 1)).toBeUndefined(); // unstamped
    expect(segmentProvenance('seg-A', 3)).toBeUndefined(); // no such member
  });

  it('clearContourProvenance flips an interpolated stamp to manual (and is a no-op otherwise)', () => {
    const interp = { metadata: { provenance: 'interpolated' } };
    expect(clearContourProvenance(interp)).toBe(true);
    expect(interp.metadata.provenance).toBe('manual');

    expect(clearContourProvenance({ metadata: { provenance: 'manual' } })).toBe(false);
    expect(clearContourProvenance({})).toBe(false);
  });

  it('a user edit (ANNOTATION_MODIFIED) flips an interpolated contour to manual; leaves others alone', () => {
    initialize();
    const handler = m.listeners.get(EV_MODIFIED);
    expect(handler, 'annotation-modified handler must be registered').toBeDefined();

    const interp = { metadata: { provenance: 'interpolated' } };
    handler!({ detail: { annotation: interp } } as unknown as Event);
    expect(interp.metadata.provenance).toBe('manual'); // edit cleared the marker

    const manual = { metadata: { provenance: 'manual' } };
    handler!({ detail: { annotation: manual } } as unknown as Event);
    expect(manual.metadata.provenance).toBe('manual'); // unchanged
  });
});
