import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * Interpolation write-through (Rebuild Phase 4 / requirement B5).
 *
 * Interpolated contours are written through (auto-accepted) the moment they're
 * generated — no promote-before-save gate, no `autoAcceptInterpolated` preference.
 * These tests pin: (1) `acceptAllAutoGenerated` promotes every auto-generated
 * contour (registers its UID + clears the `autoGenerated` flag) and skips
 * already-accepted ones; (2) the `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED`
 * handler accepts UNCONDITIONALLY — there is no preference consulted.
 */
const m = vi.hoisted(() => ({
  listeners: new Map<string, EventListener>(),
  getAllAnnotations: vi.fn((): unknown[] => []),
  getAnnotation: vi.fn((_uid?: string): unknown => undefined),
  addAnnotation: vi.fn((): boolean => true),
}));

const EV_INTERP = 'ANNOTATION_INTERPOLATION_PROCESS_COMPLETED';
const EV_SELECT = 'ANNOTATION_SELECTION_CHANGE';
const EV_MODIFIED = 'ANNOTATION_MODIFIED';

vi.mock('@cornerstonejs/core', () => ({
  eventTarget: {
    addEventListener: (type: string, cb: EventListener) => m.listeners.set(type, cb),
    removeEventListener: (type: string) => m.listeners.delete(type),
  },
}));
vi.mock('@cornerstonejs/tools', () => ({
  annotation: { state: { getAllAnnotations: m.getAllAnnotations, getAnnotation: m.getAnnotation } },
  // Literals inlined — the factory is hoisted above the const declarations below.
  Enums: { Events: { ANNOTATION_INTERPOLATION_PROCESS_COMPLETED: 'ANNOTATION_INTERPOLATION_PROCESS_COMPLETED', ANNOTATION_SELECTION_CHANGE: 'ANNOTATION_SELECTION_CHANGE', ANNOTATION_MODIFIED: 'ANNOTATION_MODIFIED' } },
}));
vi.mock('../contourRepresentation', () => ({ addAnnotation: m.addAnnotation }));

import {
  acceptAllAutoGenerated,
  acceptAnnotation,
  segmentProvenance,
  clearContourProvenance,
  canonicalizeContourOrientation,
  initialize,
  dispose,
} from '../interpolationAcceptance';

beforeEach(() => {
  m.listeners.clear();
  m.getAllAnnotations.mockReset().mockReturnValue([]);
  m.addAnnotation.mockReset().mockReturnValue(true);
});
afterEach(() => dispose());

describe('interpolation write-through (B5)', () => {
  it('acceptAnnotation promotes an auto-generated contour and is a no-op on an accepted one', () => {
    const auto = { autoGenerated: true };
    expect(acceptAnnotation(auto)).toBe(true);
    expect(auto.autoGenerated).toBe(false); // flipped → solid render
    expect(m.addAnnotation).toHaveBeenCalledTimes(1);

    m.addAnnotation.mockClear();
    expect(acceptAnnotation({ autoGenerated: false })).toBe(false); // already accepted
    expect(m.addAnnotation).not.toHaveBeenCalled();
  });

  it('acceptAllAutoGenerated promotes every auto-generated contour, skipping accepted ones', () => {
    const a = { autoGenerated: true };
    const b = { autoGenerated: false };
    const c = { autoGenerated: true };
    m.getAllAnnotations.mockReturnValue([a, b, c]);

    expect(acceptAllAutoGenerated()).toBe(2);
    expect(a.autoGenerated).toBe(false);
    expect(c.autoGenerated).toBe(false);
    expect(b.autoGenerated).toBe(false); // untouched (was already accepted)
    expect(m.addAnnotation).toHaveBeenCalledTimes(2);
  });

  it('the interpolation-completed event writes through UNCONDITIONALLY (no preference gate)', () => {
    const auto = { autoGenerated: true };
    m.getAllAnnotations.mockReturnValue([auto]);

    initialize();
    const handler = m.listeners.get(EV_INTERP);
    expect(handler, 'interpolation-completed handler must be registered').toBeDefined();

    handler!(new Event(EV_INTERP));
    // No preferencesStore is consulted — the contour is promoted purely from the event.
    expect(auto.autoGenerated).toBe(false);
    expect(m.addAnnotation).toHaveBeenCalledTimes(1);
  });
});

describe('contour provenance (signal 22)', () => {
  it('acceptAnnotation stamps a PERSISTENT interpolated provenance (survives autoGenerated clearing)', () => {
    const auto: { autoGenerated: boolean; metadata?: Record<string, unknown> } = { autoGenerated: true };
    expect(acceptAnnotation(auto)).toBe(true);
    expect(auto.autoGenerated).toBe(false); // transient flag cleared…
    expect(auto.metadata?.provenance).toBe('interpolated'); // …but provenance persists
  });

  it('segmentProvenance returns interpolated only for the matching segment with a stamped contour', () => {
    m.getAllAnnotations.mockReturnValue([
      { data: { segmentation: { segmentationId: 'seg-A', segmentIndex: 1 } }, metadata: { provenance: 'interpolated' } },
      { data: { segmentation: { segmentationId: 'seg-A', segmentIndex: 2 } }, metadata: { provenance: 'manual' } },
      { data: { segmentation: { segmentationId: 'seg-B', segmentIndex: 1 } }, metadata: {} },
    ]);
    expect(segmentProvenance('seg-A', 1)).toBe('interpolated');
    expect(segmentProvenance('seg-A', 2)).toBeUndefined(); // manual → no badge
    expect(segmentProvenance('seg-B', 1)).toBeUndefined(); // unstamped
    expect(segmentProvenance('seg-A', 3)).toBeUndefined(); // no such member
  });

  it('clearContourProvenance flips an interpolated stamp to manual (and is a no-op otherwise)', () => {
    const interp = { metadata: { provenance: 'interpolated' } };
    expect(clearContourProvenance(interp)).toBe(true);
    expect(interp.metadata.provenance).toBe('manual');

    expect(clearContourProvenance({ metadata: { provenance: 'manual' } })).toBe(false);
    expect(clearContourProvenance({})).toBe(false);
  });

});

describe('oblique orientation canonicalization (interpolation pairing fix)', () => {
  const sibling = (vpn: number[], viewUp: number[], segIdx = 1, segId = 'seg-A') => ({
    annotationUID: 'sib',
    metadata: { viewPlaneNormal: vpn, viewUp },
    data: { segmentation: { segmentationId: segId, segmentIndex: segIdx } },
  });

  it('snaps a drifted contour to a coplanar sibling of the same segment (→ === pairing works)', () => {
    const sibVpn = [0, 0.5000000067305869, -0.8660253998985326];
    const sibViewUp = [0, -0.8660253882408142, -0.5];
    m.getAllAnnotations.mockReturnValue([sibling(sibVpn, sibViewUp)]);

    // New contour: same plane, drifted by ~1e-8 (the real per-slice camera noise).
    const fresh = {
      annotationUID: 'new',
      metadata: { viewPlaneNormal: [0, 0.499999990554337, -0.8660254092378947], viewUp: [0, -0.8660253882408142, -0.5] },
      data: { segmentation: { segmentationId: 'seg-A', segmentIndex: 1 } },
    };
    expect(canonicalizeContourOrientation(fresh)).toBe(true);
    // Copied the sibling's EXACT arrays (identity), so Cornerstone's `===` match succeeds.
    expect(fresh.metadata.viewPlaneNormal).toBe(sibVpn);
    expect(fresh.metadata.viewUp).toBe(sibViewUp);
  });

  it('does NOT group a genuinely different plane (angles differ by ≫ epsilon)', () => {
    m.getAllAnnotations.mockReturnValue([sibling([0, 0, 1], [0, 1, 0])]);
    const axialElsewhere = {
      annotationUID: 'new',
      metadata: { viewPlaneNormal: [1, 0, 0], viewUp: [0, 0, 1] }, // sagittal — different plane
      data: { segmentation: { segmentationId: 'seg-A', segmentIndex: 1 } },
    };
    expect(canonicalizeContourOrientation(axialElsewhere)).toBe(false);
    expect(axialElsewhere.metadata.viewPlaneNormal).toEqual([1, 0, 0]); // untouched
  });

  it('does NOT cross segment boundaries (different segmentationId or segmentIndex)', () => {
    const sibVpn = [0, 0.5, -0.866];
    m.getAllAnnotations.mockReturnValue([
      sibling(sibVpn, [0, -0.866, -0.5], 1, 'seg-OTHER'),
      sibling(sibVpn, [0, -0.866, -0.5], 2, 'seg-A'),
    ]);
    const fresh = {
      annotationUID: 'new',
      metadata: { viewPlaneNormal: [0, 0.5000000067, -0.8660254], viewUp: [0, -0.866, -0.5] },
      data: { segmentation: { segmentationId: 'seg-A', segmentIndex: 1 } },
    };
    expect(canonicalizeContourOrientation(fresh)).toBe(false); // no same-segment coplanar sibling
  });

  it('is a no-op when there is no sibling yet (first contour of the segment)', () => {
    m.getAllAnnotations.mockReturnValue([]);
    const fresh = {
      annotationUID: 'new',
      metadata: { viewPlaneNormal: [0, 0.5, -0.866], viewUp: [0, -0.866, -0.5] },
      data: { segmentation: { segmentationId: 'seg-A', segmentIndex: 1 } },
    };
    expect(canonicalizeContourOrientation(fresh)).toBe(false);
  });
});

describe('contour provenance (signal 22) — edit flip', () => {
  it('a user edit (ANNOTATION_MODIFIED) flips an interpolated contour to manual; leaves others alone', () => {
    initialize();
    const handler = m.listeners.get(EV_MODIFIED);
    expect(handler, 'annotation-modified handler must be registered').toBeDefined();

    const interp = { metadata: { provenance: 'interpolated' } };
    handler!({ detail: { annotation: interp } } as unknown as Event);
    expect(interp.metadata.provenance).toBe('manual'); // edit cleared the marker

    const manual = { metadata: { provenance: 'manual' } };
    handler!({ detail: { annotation: manual } } as unknown as Event);
    expect(manual.metadata.provenance).toBe('manual'); // unchanged
  });
});
