import { cache, getEnabledElementByViewportId, metaData, utilities as csUtilities } from '@cornerstonejs/core';
import {
  annotation as csAnnotation,
  segmentation as csSegmentation,
  utilities as csToolUtilities,
  PlanarFreehandContourSegmentationTool,
} from '@cornerstonejs/tools';
import { useSegmentationStore } from '../../stores/segmentationStore';
import { useSegmentationManagerStore } from '../../stores/segmentationManagerStore';
import { useViewerStore } from '../../stores/viewerStore';
import { usePreferencesStore } from '../../stores/preferencesStore';
import { useConnectionStore } from '../../stores/connectionStore';
import { segmentationManager } from '../segmentation/segmentationManagerSingleton';
import { segmentationService } from '../cornerstone/segmentationService';
import {
  getTopUndoHistoryEntry,
  type HistoryMemoEntry,
  type HistoryMemoRecord,
} from '../cornerstone/segmentationService/historyMemo';
import * as contourRep from '../cornerstone/contourRepresentation';
import { toolService } from '../cornerstone/toolService';
import { viewportLayoutService } from '../cornerstone/viewportLayoutService';
import { LayoutType, ToolName, panelId as makePanelId } from '@shared/types/viewer';
import {
  loadLocalDicomFiles as bridgeLoadLocalDicomFiles,
  type LoadLocalDicomFilesResult,
} from './e2eFixtureBridge';
import {
  classifySegmentationOnViewport,
  classifyAnnotationOnViewport,
  type EligibilityClass,
} from '../cornerstone/segmentationService/visibility';
import { resolveAction, type StyleAction } from '../cornerstone/segmentationService/styling';
import { rtStructService } from '../cornerstone/rtStructService';
import { containerService } from '../cornerstone/containerService';
import * as containerBridge from '../cornerstone/containerBridge';
import * as transport from '../cornerstone/segmentationService/transport';
import { undoService } from '../cornerstone/undoService';
import type { SaveOutcome } from '../cornerstone/transportContractService';

type ActiveSegmentationState = {
  activeSegmentationId: string | null;
  activeSegmentIndex: number;
};

type ActiveContourSnapshot = ActiveSegmentationState & {
  currentImageId: string | null;
  currentSliceIndex: number | null;
  total: number;
  onCurrentSlice: number;
  autoGeneratedTotal: number;
  autoGeneratedOnCurrentSlice: number;
  sliceIndices: number[];
  autoGeneratedSliceIndices: number[];
  selected: string[];
};

type UndoStackInfo = {
  canUndo: boolean;
  canRedo: boolean;
  topEntryDescription: string | null;
};

type DirtyState = {
  /** segmentationStore.hasUnsavedChanges (single global flag, design §A9/E1). */
  globalDirty: boolean;
  /** segmentationManagerStore.dirtySegIds keys whose value is true. */
  perSegmentationDirty: string[];
};

type SegmentationSnapshotEntry = {
  segmentationId: string;
  label: string;
  /** Number of segments per csSegmentation.state.getSegmentation(...).segments. */
  segmentCount: number;
  /** Viewport ids the segmentation currently has a representation on. */
  viewportIds: string[];
  /** Number of contour annotations in csAnnotation.state tied to this segmentationId. */
  contourAnnotationCount: number;
  /** Slice indices that have at least one contour annotation. */
  contourSliceIndices: number[];
};

type ActiveByPanelEntry = {
  panelId: string;
  /** True iff `panelId` is in the current layoutConfig.panelCount. */
  isCurrentLayoutPanel: boolean;
  segmentationId: string | null;
  segmentIndex: number;
};

type ToggleMprResult = {
  /** True if multiViewport.enabled was set when toggleMpr ran. */
  flagEnabled: boolean;
  /**
   * True iff the mpr-2x2 preset is the current preset id after the toggle.
   * The legacy `mprActive` field on viewerStore was removed in Phase 6.4.
   */
  entered: boolean;
  /** Why the toggle was a no-op when applicable; null on success. */
  reason: string | null;
};

let lockAwareUndoRedoCounter = 0;

// Synthetic SaveAdapter call-stats for signal G14 / G15 E2E. Populated
// when `installTestSaveAdapter()` runs; reset on each install so test
// re-runs start fresh.
let testSaveAdapterStats: null | {
  saveCount: number;
  inFlight: number;
  perContainer: Record<string, number>;
} = null;

declare global {
  interface Window {
    __XNAT_E2E__?: {
      setMultiViewportEnabled: (enabled: boolean) => void;
      getMultiViewportEnabled: () => boolean;
      getSegmentationCount: () => number;
      getSegmentationIdByLabel: (label: string) => string | null;
      getActiveSegmentationState: () => ActiveSegmentationState;
      getActiveContourSnapshot: (panelId?: string, segmentationId?: string | null) => ActiveContourSnapshot;
      setSelectionTool: () => void;
      activateSegmentation: (panelId: string, segmentationId: string, segmentIndex?: number) => void;
      setSegmentLocked: (segmentationId: string, segmentIndex: number, locked: boolean) => void;
      createLockAwareUndoRedoTestMemo: (segmentationId: string, segmentIndex: number) => boolean;
      getLockAwareUndoRedoCounter: () => number;
      createTestStructure: (panelId: string, label: string) => Promise<string>;
      createTestContour: (panelId: string, segmentationId: string, segmentIndex?: number) => string | null;
      /**
       * Sync. Drive a panel's viewport to a specific slice index. Wraps
       * Cornerstone's `viewport.setImageIdIndex` and renders. Returns
       * true when the call landed on a viewport with the API; false when
       * the panel has no enabled element (yet) or the viewport doesn't
       * expose `setImageIdIndex` (e.g., a placeholder div).
       *
       * Acceptance signal G2 needs precise per-panel slice positioning,
       * which `page.mouse.wheel` does not give without knowing the
       * slice-per-tick mapping.
       */
      setSliceIndex: (panelId: string, sliceIndex: number) => boolean;
      /** Sync. Read a panel's current slice index, or null if unknown. */
      getSliceIndex: (panelId: string) => number | null;
      /**
       * Returns true when imagePlaneModule metadata is registered for every
       * imageId in the panel's stack — the precondition for
       * `viewport.getViewReference({ sliceIndex })` to return a value for any
       * sliceIndex. Tests that rely on cross-slice operations (interpolation,
       * crosshair sync) should poll this before continuing so they don't race
       * with the background image preloader.
       */
      isViewportImagePlaneMetadataReady: (panelId: string) => boolean;
      closePanel: (panelId: string) => boolean;
      getUndoStackInfo: () => UndoStackInfo;

      // ─── Layout-switching hooks (Signal 6) ─────────────────────
      /** Sync. Drives the same setLayout the toolbar dropdown calls. */
      setLayout: (layout: LayoutType) => void;
      /**
       * Async. Mirrors App.tsx handleToggleMPR. After Phase 6.4 the legacy
       * enterMPR / MPRViewportGrid path is gone; only the
       * `viewportLayoutService.applyPreset('mpr-2x2')` + setLayout +
       * per-panel orientation propagation path remains. Exit clears
       * orientations and applies '2x2'.
       *
       * Returns the resulting state so callers can assert without polling.
       */
      toggleMpr: () => Promise<ToggleMprResult>;
      /**
       * Sync. Returns the union of segmentationStore.hasUnsavedChanges (the
       * single global dirty flag per design §A9 / §E1) and
       * segmentationManagerStore.dirtySegIds. The "single dirty flag" half of
       * Signal 6 asserts on this shape — exactly one segmentation marked
       * dirty, no phantoms keyed off removed panels.
       */
      getDirtyState: () => DirtyState;
      /**
       * Sync. Per-segmentation snapshot that survives layout churn. Used by
       * Signal 6 for the "no structures lost, no duplicates" assertion: take
       * a snapshot before the rapid layout sequence, take another after,
       * compare segmentCount + contourAnnotationCount + segmentationId set.
       *
       * Excludes Cornerstone's internal multi-layer-group sub-segmentations
       * (whose ids contain "_layer_") so the snapshot matches the user-facing
       * segmentation list that segmentationStore exposes.
       */
      getSegmentationSnapshot: () => SegmentationSnapshotEntry[];
      /**
       * Sync. Per-panel active-segmentation table from
       * segmentationManagerStore. The `isCurrentLayoutPanel` flag exposes
       * the "no stale highlights" half of Signal 6: any entry where
       * `isCurrentLayoutPanel === false` is a leftover from a panel that
       * has since been destroyed by setLayout.
       */
      getActiveByPanel: () => ActiveByPanelEntry[];
      /**
       * Async. Calls segmentationService.exportToDicomSeg(segId) and
       * returns the base64 string (or null on failure). Same code path
       * the segmentation panel's "Save → Upload to XNAT" runs; lets
       * Signal 6 assert "save once produces correct file" by comparing
       * encoded length before vs. after the rapid layout sequence.
       */
      exportSegmentationToBase64: (segmentationId: string) => Promise<string | null>;
      /**
       * Sync. Marks a segmentation dirty via both the global flag and
       * the per-id manager store — the same two writes the autoSave
       * event handler does (autoSave.ts:429+434). Used for the flag-on
       * Signal 6 variant where the contour-creation path bypasses the
       * ANNOTATION_COMPLETED autosave handler.
       */
      markSegmentationDirty: (segmentationId: string) => void;
      /**
       * Sync. Calls segmentationStore._markClean() — same call the
       * post-save path makes (segmentationService.ts:433). For test
       * teardown after using markSegmentationDirty, so the next test's
       * page.reload() doesn't race against a beforeunload prompt.
       */
      markAllSegmentationsClean: () => void;

      /**
       * Async. Loads DICOM files from absolute disk paths into the named
       * panel via the local-fixture bridge. Reads bytes through an IPC
       * channel that's only registered when the main process is launched
       * with `E2E_TESTING=1`; reads are restricted to the configured
       * fixture root. Replaces whatever was previously loaded in the
       * panel. Returns the resolved image IDs so the spec can assert.
       *
       * Mirrors the local-file-import path App.tsx already uses for
       * drag-and-drop / file-picker imports — same wadouri.fileManager
       * registration, same dicomwebLoader.orderImageIdsByDicomMetadata,
       * same setPanelImageIds wire-up — so the fixture flows through
       * production code paths.
       */
      loadLocalDicomFiles: (panelId: string, paths: string[]) => Promise<LoadLocalDicomFilesResult>;
      /**
       * Sync. Forces the connection store into the 'connected' state
       * with a synthetic connection object so the viewer gate
       * (App.tsx isConnected) opens without an XNAT round-trip. For
       * local-fixture E2E specs that don't need real XNAT auth.
       *
       * Use only when the spec is exercising local-fixture flows; specs
       * that test XNAT integration (login, browse, upload) must continue
       * to use the real authenticatedPage fixture.
       */
      setFakeConnected: (connected: boolean) => void;

      /**
       * Sync. Resolves the cross-series classification + style action for
       * a (segmentation, viewport) pair. Wraps `classifySegmentationOnViewport`
       * + `resolveAction` from segmentationService/visibility.ts and
       * styling.ts. Read-only — does not mutate Cornerstone or the policy.
       *
       * The `eligibility` field is one of 'native' | 'cross-series-A2b' |
       * 'cross-series-A2c' | 'cross-FoR' | null.
       *
       * The `action.kind` field is one of 'reset' | 'apply-cross-series' |
       * 'hide'. For signal §G #9 (T1+T2 same FoR) we expect
       * eligibility='cross-series-A2b' + action.kind='apply-cross-series'.
       * For signal §G #10 (sameforuid-different-acquisition off-by-default)
       * we expect eligibility='cross-series-A2c' + action.kind='hide'.
       */
      getCrossSeriesAction: (segmentationId: string, viewportId: string) => {
        eligibility: EligibilityClass | null;
        action: StyleAction;
      };

      /**
       * Sync. Same as getCrossSeriesAction but for a contour annotation.
       */
      getCrossSeriesActionForAnnotation: (annotationUID: string, viewportId: string) => {
        eligibility: EligibilityClass | null;
        action: StyleAction;
      };

      /**
       * Sync. Wraps `segmentationService.shouldBlockDrawingOnViewport` —
       * resolves the drawing-routing decision for the given viewport
       * against the current `useSegmentationStore.activeSegmentationId`.
       * Used by signal G12 (drawing block on non-native series) to assert
       * that gesture-start would be blocked with a hint.
       *
       * Returns either `{ kind: 'allow' }` or
       * `{ kind: 'block', reason, hintMessage }`.
       */
      getDrawingRoutingDecision: (viewportId: string) =>
        | { kind: 'allow' }
        | {
            kind: 'block';
            reason: 'no-for-matched-viewport-open' | 'cross-series' | 'cross-for';
            hintMessage: string;
          };

      /**
       * Async. Wraps `rtStructService.exportToRtStruct(segId)`. Returns
       * the serialized RTSTRUCT as a base64 string so specs can
       * round-trip via dcmjs without going through XNAT. Used by signals
       * G13 / G18 / G19 / G22 (RTSTRUCT save → parse → reload).
       */
      exportRtStructToBase64: (segmentationId: string) => Promise<string | null>;

      /**
       * Sync. Wraps `containerService.setRoiType(memberId, roiType)` so
       * specs can drive typed-ROI mutations through the production code
       * path. Used by G18 (RTROIInterpretedType round-trip).
       */
      setMemberRoiType: (memberId: string, roiType: string) => void;

      /**
       * Sync. Wraps `containerService.approveContainer(containerId, by)`
       * so specs can drive the approval workflow through the production
       * code path. Used by G19 (approval persistence).
       */
      approveContainer: (containerId: string, by: string | null) => void;

      /**
       * Sync. Returns the active container's ID, or null if none. Used
       * by RTSTRUCT round-trip specs that need to address the container
       * by id (approval / revoke / save).
       */
      getActiveContainerId: () => string | null;

      /**
       * Sync. Returns the member metadata for the active container's
       * members — id, segmentIndex, roiType, provenance — without
       * exposing the full Container object (which includes Cornerstone
       * cross-references). Used by RTSTRUCT round-trip specs.
       */
      getActiveContainerMembers: () => Array<{
        id: string;
        segmentIndex: number | null;
        roiType: string | null;
        provenance: string;
        name: string;
      }>;

      /**
       * Sync. Installs a synthetic in-process `SaveAdapter` and short
       * debounce window so signal G14 (queue-next-save) and G15 (undo
       * crosses save point) can drive the production transport pipeline
       * end-to-end without an XNAT round-trip. The adapter records every
       * `save(containerId)` call and resolves with `{ kind: 'success', ... }`
       * after a small delay so concurrent `notifyDirty` calls exercise
       * the saving / saving-pending states.
       *
       * Returns a session-id string the spec uses with
       * `getTransportTestStats(sessionId)` to read recorded save counts.
       * Calling `installTestSaveAdapter` again replaces the prior adapter
       * and resets stats.
       */
      installTestSaveAdapter: (saveDelayMs?: number, debounceMs?: number) => string;

      /**
       * Sync. Reads the synthetic SaveAdapter's recorded stats:
       * - saveCount: number of times save() has been invoked
       * - inFlight: number of saves currently awaiting their delay
       * - perContainer: per-containerId save call counts
       * Returns null if no test adapter has been installed.
       */
      getTransportTestStats: () => null | {
        saveCount: number;
        inFlight: number;
        perContainer: Record<string, number>;
      };

      /**
       * Async. Wraps `transport.flushNow(containerId)` — manual Save path
       * that bypasses the debounce. Resolves to the SaveOutcome (or null
       * when a save was already in flight and this call only set
       * pending). Used to anchor save points in the G15 undo flow.
       */
      transportFlushNow: (containerId: string) => Promise<unknown>;

      /**
       * Sync. Wraps `transport.notifyDirty(containerId)` — schedules a
       * debounced save the same way the production autoSave path does
       * after a real edit. Used by E2E specs whose edit pipeline
       * (`createTestContour`) bypasses the autoSave event listeners and
       * therefore needs to drive the dirty notification explicitly.
       */
      transportNotifyDirty: (containerId: string) => void;

      /**
       * Async. Wait until the synthetic adapter's in-flight count drops
       * to zero AND no debounce timer is queued for the given container.
       * Useful before asserting end-state save counts.
       */
      waitForTransportIdle: (containerId: string, timeoutMs?: number) => Promise<boolean>;

      /** Sync. Reads `containerBridge.getContainer(id).dirty`. */
      getContainerDirty: (containerId: string) => boolean | null;

      /**
       * Async. Wraps the global `undoService.undo()` call so specs can
       * step backward through the undo stack from the renderer. Returns
       * true on a successful undo, false if there's nothing to undo.
       */
      undoOnce: () => boolean;
    };
  }
}

type Point3 = [number, number, number];

function scalePoint(point: Point3, scalar: number): Point3 {
  return [point[0] * scalar, point[1] * scalar, point[2] * scalar];
}

function addPoint(a: Point3, b: Point3): Point3 {
  return [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
}

function getActiveSegmentationState(): ActiveSegmentationState {
  const state = useSegmentationStore.getState();
  return {
    activeSegmentationId: state.activeSegmentationId,
    activeSegmentIndex: state.activeSegmentIndex,
  };
}

function getActiveContourSnapshot(panelId = 'panel_0', targetSegmentationId?: string | null): ActiveContourSnapshot {
  const { activeSegmentationId, activeSegmentIndex } = getActiveSegmentationState();
  const viewport =
    (getEnabledElementByViewportId(panelId) as {
      viewport?: {
        getCurrentImageId?: () => string | null;
        getCurrentImageIdIndex?: () => number;
      };
    } | undefined)
      ?.viewport
    ?? null;
  const viewerState = useViewerStore.getState();
  const storeSliceIndex = viewerState.viewports[panelId]?.imageIndex;
  const currentSliceIndex = Number.isInteger(viewport?.getCurrentImageIdIndex?.())
    ? Number(viewport?.getCurrentImageIdIndex?.())
    : (Number.isInteger(storeSliceIndex) ? Number(storeSliceIndex) : null);
  const currentImageId =
    viewport?.getCurrentImageId?.()
    ?? (
      currentSliceIndex != null
        ? (viewerState.panelImageIdsMap[panelId] ?? [])[currentSliceIndex] ?? null
        : null
    );
  const allContourAnnotations = csAnnotation.state.getAllAnnotations().filter((annotation: any) => (
    typeof annotation?.metadata?.toolName === 'string'
    && annotation.metadata.toolName.includes('Contour')
  ));
  const selectedAnnotationUIDs = csAnnotation.selection.getAnnotationsSelected?.() ?? [];
  const selectedContourAnnotation = allContourAnnotations.find(
    (annotation: any) => selectedAnnotationUIDs.includes(annotation?.annotationUID),
  );
  const resolvedActiveSegmentationId =
    targetSegmentationId
    ?? activeSegmentationId
    ?? selectedContourAnnotation?.data?.segmentation?.segmentationId
    ?? allContourAnnotations[0]?.data?.segmentation?.segmentationId
    ?? null;
  const resolvedActiveSegmentIndex =
    activeSegmentIndex > 0
      ? activeSegmentIndex
      : Number(selectedContourAnnotation?.data?.segmentation?.segmentIndex ?? 0);

  const contourAnnotations = allContourAnnotations.filter((annotation: any) => (
    annotation?.data?.segmentation?.segmentationId === resolvedActiveSegmentationId
    && typeof annotation?.metadata?.toolName === 'string'
    && annotation.metadata.toolName.includes('Contour')
  ));
  const autoGeneratedAnnotations = contourAnnotations.filter((annotation: any) => annotation?.autoGenerated === true);

  return {
    activeSegmentationId: resolvedActiveSegmentationId,
    activeSegmentIndex: resolvedActiveSegmentIndex,
    currentImageId,
    currentSliceIndex,
    total: contourAnnotations.length,
    onCurrentSlice: contourAnnotations.filter(
      (annotation: any) => annotation?.metadata?.referencedImageId === currentImageId,
    ).length,
    autoGeneratedTotal: autoGeneratedAnnotations.length,
    autoGeneratedOnCurrentSlice: autoGeneratedAnnotations.filter(
      (annotation: any) => annotation?.metadata?.referencedImageId === currentImageId,
    ).length,
    sliceIndices: contourAnnotations
      .map((annotation: any) => annotation?.metadata?.sliceIndex)
      .filter((sliceIndex: unknown): sliceIndex is number => Number.isInteger(sliceIndex))
      .sort((a: number, b: number) => a - b),
    autoGeneratedSliceIndices: autoGeneratedAnnotations
      .map((annotation: any) => annotation?.metadata?.sliceIndex)
      .filter((sliceIndex: unknown): sliceIndex is number => Number.isInteger(sliceIndex))
      .sort((a: number, b: number) => a - b),
    selected: selectedAnnotationUIDs,
  };
}

const LAYOUT_BY_PANEL_COUNT: Record<number, LayoutType> = {
  1: '1x1',
  2: '1x2',
  3: '1x2',
  4: '2x2',
};

function describeUndoEntry(entry: HistoryMemoEntry): string | null {
  if (!entry) return null;
  const records = (Array.isArray(entry) ? entry : [entry])
    .filter((memo): memo is HistoryMemoRecord => !!memo && typeof memo === 'object');
  if (records.length === 0) return null;
  const first = records[0];
  const op = typeof first.operationType === 'string' && first.operationType.length > 0 ? first.operationType : 'memo';
  const labelParts: string[] = [];
  if (typeof first.label === 'string' && first.label.length > 0) {
    labelParts.push(first.label);
  } else if (typeof first.segmentationId === 'string' && first.segmentationId.length > 0) {
    labelParts.push(first.segmentationId);
  }
  if (Number.isInteger(first.segmentIndex) && Number(first.segmentIndex) > 0) {
    labelParts.push(`segment ${first.segmentIndex}`);
  }
  return labelParts.length > 0 ? `${op}:${labelParts.join('|')}` : op;
}

function getUndoStackInfo(): UndoStackInfo {
  const memo = (csUtilities as unknown as { HistoryMemo?: { DefaultHistoryMemo?: { canUndo?: boolean; canRedo?: boolean } } })
    .HistoryMemo?.DefaultHistoryMemo;
  return {
    canUndo: !!memo?.canUndo,
    canRedo: !!memo?.canRedo,
    topEntryDescription: describeUndoEntry(getTopUndoHistoryEntry()),
  };
}

function getDirtyState(): DirtyState {
  const segStore = useSegmentationStore.getState();
  const mgrStore = useSegmentationManagerStore.getState();
  const perSegmentationDirty = Object.entries(mgrStore.dirtySegIds)
    .filter(([, isDirty]) => !!isDirty)
    .map(([segId]) => segId);
  return {
    globalDirty: segStore.hasUnsavedChanges,
    perSegmentationDirty,
  };
}

function getSegmentationSnapshot(): SegmentationSnapshotEntry[] {
  // The user-facing list lives in segmentationStore.segmentations (synced
  // from csSegmentation by segmentationService) and excludes
  // multi-layer-group sub-segmentations. Use it as the structural source of
  // truth so the snapshot matches what the segmentation panel shows.
  const segStore = useSegmentationStore.getState();
  const allAnnotations = csAnnotation.state.getAllAnnotations() as any[];

  return segStore.segmentations.map((segment) => {
    let viewportIds: string[] = [];
    try {
      viewportIds = segmentationService.getViewportIdsForSegmentation(segment.segmentationId) ?? [];
    } catch {
      // Sub-segmentations of a multi-layer group get listed by some Cornerstone APIs
      // and not others; treat lookup failures as "no attachment".
      viewportIds = [];
    }

    const matchingAnnotations = allAnnotations.filter((annotation) => (
      annotation?.data?.segmentation?.segmentationId === segment.segmentationId
      && typeof annotation?.metadata?.toolName === 'string'
      && annotation.metadata.toolName.includes('Contour')
    ));
    const sliceIndices = Array.from(new Set(
      matchingAnnotations
        .map((annotation: any) => annotation?.metadata?.sliceIndex)
        .filter((sliceIndex: unknown): sliceIndex is number => Number.isInteger(sliceIndex)),
    )).sort((a, b) => a - b);

    return {
      segmentationId: segment.segmentationId,
      label: segment.label,
      segmentCount: segment.segments.length,
      viewportIds: [...viewportIds].sort(),
      contourAnnotationCount: matchingAnnotations.length,
      contourSliceIndices: sliceIndices,
    };
  });
}

function getActiveByPanel(): ActiveByPanelEntry[] {
  const viewerState = useViewerStore.getState();
  const mgrStore = useSegmentationManagerStore.getState();
  const currentPanelIds = new Set(
    Array.from({ length: viewerState.layoutConfig.panelCount }, (_, i) => makePanelId(i)),
  );
  const allPanelIds = new Set<string>([
    ...currentPanelIds,
    ...Object.keys(mgrStore.activeSegmentationIdByPanel),
    ...Object.keys(mgrStore.activeSegmentIndexByPanel),
  ]);
  return Array.from(allPanelIds).sort().map((pid) => ({
    panelId: pid,
    isCurrentLayoutPanel: currentPanelIds.has(pid),
    segmentationId: mgrStore.activeSegmentationIdByPanel[pid] ?? null,
    segmentIndex: mgrStore.activeSegmentIndexByPanel[pid] ?? 0,
  }));
}

async function toggleMpr(): Promise<ToggleMprResult> {
  const flagEnabled = usePreferencesStore.getState().preferences.multiViewport.enabled;
  const store = useViewerStore.getState();

  // After Phase 6.4 the only MPR path is viewportLayoutService's mpr-2x2
  // preset; the legacy enterMPR / MPRViewportGrid path is gone.
  const isMprPresetActive = viewportLayoutService.getCurrentPresetId() === 'mpr-2x2';
  if (isMprPresetActive) {
    // Exit: clear orientations on panels 0/1/2 (back to STACK), then 2x2.
    store.setPanelOrientation(makePanelId(0), 'STACK');
    store.setPanelOrientation(makePanelId(1), 'STACK');
    store.setPanelOrientation(makePanelId(2), 'STACK');
    viewportLayoutService.applyPreset('2x2');
    return { flagEnabled, entered: false, reason: null };
  }

  const activePanelId = store.activeViewportId ?? makePanelId(0);
  const activeImageIds = store.panelImageIdsMap[activePanelId] ?? [];
  if (activeImageIds.length < 2) {
    return { flagEnabled, entered: false, reason: 'fewer than 2 slices on active panel' };
  }
  if (store.layoutConfig.panelCount < 4) {
    store.setLayout('2x2');
  }
  const orientations: Array<'AXIAL' | 'SAGITTAL' | 'CORONAL'> = ['AXIAL', 'SAGITTAL', 'CORONAL'];
  for (let i = 0; i < orientations.length; i++) {
    const target = makePanelId(i);
    if (target !== activePanelId) {
      store.setPanelImageIds(target, activeImageIds);
    }
    store.setPanelOrientation(target, orientations[i]);
  }
  viewportLayoutService.applyPreset('mpr-2x2');
  return { flagEnabled, entered: true, reason: null };
}

export function installRendererE2eHooks(): void {
  if (typeof window === 'undefined') {
    return;
  }

  window.__XNAT_E2E__ = {
    // ─── Multi-viewport rewrite hooks (Phase 1) ───────────────────
    setMultiViewportEnabled: (enabled: boolean) => {
      usePreferencesStore.getState().setMultiViewportEnabled(enabled);
    },
    getMultiViewportEnabled: () => usePreferencesStore.getState().preferences.multiViewport.enabled,

    getSegmentationCount: () => useSegmentationStore.getState().segmentations.length,
    getSegmentationIdByLabel: (label: string) => (
      useSegmentationStore.getState().segmentations.find((segmentation) => segmentation.label === label)?.segmentationId
      ?? null
    ),
    getActiveSegmentationState,
    getActiveContourSnapshot,
    setSelectionTool: () => {
      toolService.setActiveTool(ToolName.SegmentSelect);
    },
    activateSegmentation: (panelId: string, segmentationId: string, segmentIndex = 1) => {
      useSegmentationStore.getState().setActiveSegmentation(segmentationId);
      segmentationManager.userSelectedSegmentation(panelId, segmentationId, segmentIndex);
    },
    setSegmentLocked: (segmentationId: string, segmentIndex: number, locked: boolean) => {
      const isLocked = segmentationService.getSegmentLocked(segmentationId, segmentIndex);
      if (isLocked !== locked) {
        segmentationService.toggleSegmentLocked(segmentationId, segmentIndex);
      }
    },
    createLockAwareUndoRedoTestMemo: (segmentationId: string, segmentIndex: number) => {
      const historyMemo = (csUtilities as any).HistoryMemo?.DefaultHistoryMemo;
      if (!historyMemo?.push) {
        return false;
      }

      const label =
        useSegmentationStore.getState().segmentations
          .find((segmentation) => segmentation.segmentationId === segmentationId)
          ?.segments.find((segment) => segment.segmentIndex === segmentIndex)
          ?.label
        ?? `Segment ${segmentIndex}`;

      lockAwareUndoRedoCounter = 0;
      historyMemo.push({
        id: `e2e-history-${segmentationId}-${segmentIndex}`,
        operationType: 'annotation',
        segmentationId,
        segmentIndex,
        label,
        restoreMemo: () => {
          lockAwareUndoRedoCounter += 1;
        },
      });
      return true;
    },
    getLockAwareUndoRedoCounter: () => lockAwareUndoRedoCounter,
    setSliceIndex: (panelId: string, sliceIndex: number) => {
      const enabledElement = getEnabledElementByViewportId(panelId) as
        | {
            viewport?: {
              setImageIdIndex?: (i: number) => unknown;
              setSliceIndex?: (i: number) => unknown;
              render?: () => void;
            };
          }
        | undefined;
      const viewport = enabledElement?.viewport;
      if (!viewport) return false;
      // Stack viewports use setImageIdIndex; volume viewports use setSliceIndex.
      // Try the stack API first since it's the common case for the local
      // fixture (CT-axial-300 mounts as a stack viewport by default).
      if (typeof viewport.setImageIdIndex === 'function') {
        viewport.setImageIdIndex(sliceIndex);
        viewport.render?.();
        return true;
      }
      if (typeof viewport.setSliceIndex === 'function') {
        viewport.setSliceIndex(sliceIndex);
        viewport.render?.();
        return true;
      }
      return false;
    },
    getSliceIndex: (panelId: string) => {
      const enabledElement = getEnabledElementByViewportId(panelId) as
        | {
            viewport?: {
              getCurrentImageIdIndex?: () => number;
              getSliceIndex?: () => number;
            };
          }
        | undefined;
      const viewport = enabledElement?.viewport;
      const stackIdx = viewport?.getCurrentImageIdIndex?.();
      if (Number.isInteger(stackIdx) && Number(stackIdx) >= 0) return Number(stackIdx);
      const volumeIdx = viewport?.getSliceIndex?.();
      if (Number.isInteger(volumeIdx) && Number(volumeIdx) >= 0) return Number(volumeIdx);
      const storeIdx = useViewerStore.getState().viewports[panelId]?.imageIndex;
      return Number.isInteger(storeIdx) ? Number(storeIdx) : null;
    },
    isViewportImagePlaneMetadataReady: (panelId: string): boolean => {
      const imageIds = useViewerStore.getState().panelImageIdsMap[panelId] ?? [];
      if (imageIds.length === 0) return false;
      for (const imageId of imageIds) {
        if (!metaData.get('imagePlaneModule', imageId)) return false;
      }
      return true;
    },
    createTestStructure: async (panelId: string, label: string) => {
      const sourceImageIds = useViewerStore.getState().panelImageIdsMap[panelId] ?? [];
      if (sourceImageIds.length === 0) {
        throw new Error(`No source images available for ${panelId}`);
      }

      const segmentationId = await segmentationManager.createNewStructure(panelId, sourceImageIds, label);
      const segmentIndex = await segmentationManager.addSegment(segmentationId, `${label} Segment`);
      useSegmentationStore.getState().setActiveSegmentation(segmentationId);
      segmentationManager.userSelectedSegmentation(panelId, segmentationId, segmentIndex);
      return segmentationId;
    },
    createTestContour: (panelId: string, segmentationId: string, segmentIndex = 1) => {
      const enabledElement = getEnabledElementByViewportId(panelId) as
        | {
            viewport?: {
              getCurrentImageId?: () => string | null;
              getCurrentImageIdIndex?: () => number;
              getViewReference?: (options?: { sliceIndex?: number }) => Record<string, unknown> | undefined;
              getCamera?: () => { viewPlaneNormal?: unknown; viewUp?: unknown } | undefined;
              canvasToWorld?: (point: [number, number]) => Point3;
              render?: () => void;
            };
          }
        | undefined;
      const viewport = enabledElement?.viewport;
      const viewerState = useViewerStore.getState();
      const storeSliceIndex = viewerState.viewports[panelId]?.imageIndex;
      const currentSliceIndex = Number.isInteger(viewport?.getCurrentImageIdIndex?.())
        ? Number(viewport?.getCurrentImageIdIndex?.())
        : (Number.isInteger(storeSliceIndex) ? Number(storeSliceIndex) : null);
      const viewReference = currentSliceIndex != null
        ? viewport?.getViewReference?.({ sliceIndex: currentSliceIndex })
        : viewport?.getViewReference?.();
      const camera = viewport?.getCamera?.();
      const viewPlaneNormal = Array.isArray((viewReference as { viewPlaneNormal?: unknown } | undefined)?.viewPlaneNormal)
        ? (viewReference as { viewPlaneNormal: Point3 }).viewPlaneNormal
        : (Array.isArray(camera?.viewPlaneNormal) ? camera.viewPlaneNormal as Point3 : undefined);
      const viewUp = Array.isArray((viewReference as { viewUp?: unknown } | undefined)?.viewUp)
        ? (viewReference as { viewUp: Point3 }).viewUp
        : (Array.isArray(camera?.viewUp) ? camera.viewUp as Point3 : undefined);
      const currentImageId =
        viewport?.getCurrentImageId?.()
        ?? (() => {
          const imageIds = viewerState.panelImageIdsMap[panelId] ?? [];
          const imageIndex = viewerState.viewports[panelId]?.imageIndex ?? 0;
          return imageIds[imageIndex] ?? null;
        })();
      if (!currentImageId) return null;

      const canvas = document.querySelector(
        `[data-testid="stack-viewport-canvas:${panelId}"] canvas`,
      ) as HTMLCanvasElement | null;

      if (canvas && typeof viewport?.canvasToWorld === 'function') {
        const width = canvas.clientWidth || canvas.width || 0;
        const height = canvas.clientHeight || canvas.height || 0;
        if (width > 0 && height > 0) {
          const points: Point3[] = [
            viewport.canvasToWorld([width * 0.38, height * 0.38]),
            viewport.canvasToWorld([width * 0.54, height * 0.38]),
            viewport.canvasToWorld([width * 0.54, height * 0.54]),
            viewport.canvasToWorld([width * 0.38, height * 0.54]),
          ];
          if (points.every(Boolean)) {
            const annotationUID = csUtilities.uuidv4();
            const annotation: any = {
              annotationUID,
              metadata: {
                toolName: PlanarFreehandContourSegmentationTool.toolName,
                referencedImageId: currentImageId,
                FrameOfReferenceUID: metaData.get('imagePlaneModule', currentImageId)?.frameOfReferenceUID,
                sliceIndex: currentSliceIndex ?? undefined,
                viewPlaneNormal,
                viewUp,
              },
              data: {
                contour: {
                  polyline: points,
                  closed: true,
                },
                segmentation: {
                  segmentationId,
                  segmentIndex,
                },
                handles: {
                  points: [],
                  activeHandleIndex: null,
                },
              },
              highlighted: true,
              isSelected: true,
              isLocked: false,
              isVisible: true,
              invalidated: false,
            };

            const annotationGroupSelector = viewport?.element ?? panelId;
            csAnnotation.state.addAnnotation?.(annotation, annotationGroupSelector);
            contourRep.attachAnnotationUID(segmentationId, segmentIndex, annotationUID);

            segmentationService.setActiveSegmentIndex(segmentationId, segmentIndex);
            segmentationService.activateOnViewport(panelId, segmentationId);
            csAnnotation.selection.setAnnotationSelected?.(annotationUID, true, false);
            csToolUtilities.triggerAnnotationRenderForViewportIds?.([panelId]);
            viewport.render?.();
            segmentationService.sync();

            return annotationUID;
          }
        }
      }

      const plane = metaData.get('imagePlaneModule', currentImageId) as
        | {
            imagePositionPatient?: Point3;
            rowCosines?: Point3;
            columnCosines?: Point3;
            frameOfReferenceUID?: string;
            rowPixelSpacing?: number;
            columnPixelSpacing?: number;
          }
        | undefined;
      const image = cache.getImage(currentImageId) as
        | {
            rows?: number;
            columns?: number;
            rowPixelSpacing?: number;
            columnPixelSpacing?: number;
          }
        | undefined;
      if (!plane?.imagePositionPatient || !plane.rowCosines || !plane.columnCosines) {
        return null;
      }

      const rowSpacing = Number(plane.rowPixelSpacing ?? image?.rowPixelSpacing ?? 1);
      const columnSpacing = Number(plane.columnPixelSpacing ?? image?.columnPixelSpacing ?? 1);
      const rows = Number(image?.rows ?? 256);
      const columns = Number(image?.columns ?? 256);

      const rowAxis = plane.rowCosines;
      const columnAxis = plane.columnCosines;
      const origin = plane.imagePositionPatient;
      const center = addPoint(
        addPoint(origin, scalePoint(rowAxis, columns * columnSpacing * 0.45)),
        scalePoint(columnAxis, rows * rowSpacing * 0.45),
      );
      const size = Math.max(6, Math.min(rows * rowSpacing, columns * columnSpacing) * 0.06);

      const points: Point3[] = [
        addPoint(addPoint(center, scalePoint(rowAxis, -size)), scalePoint(columnAxis, -size)),
        addPoint(addPoint(center, scalePoint(rowAxis, size)), scalePoint(columnAxis, -size)),
        addPoint(addPoint(center, scalePoint(rowAxis, size)), scalePoint(columnAxis, size)),
        addPoint(addPoint(center, scalePoint(rowAxis, -size)), scalePoint(columnAxis, size)),
      ];

      const annotationUID = csUtilities.uuidv4();
      const annotation: any = {
        annotationUID,
        metadata: {
          toolName: PlanarFreehandContourSegmentationTool.toolName,
          referencedImageId: currentImageId,
          FrameOfReferenceUID: plane.frameOfReferenceUID,
          sliceIndex: currentSliceIndex ?? undefined,
          viewPlaneNormal,
          viewUp,
        },
        data: {
          contour: {
            polyline: points,
            closed: true,
          },
          segmentation: {
            segmentationId,
            segmentIndex,
          },
          handles: {
            points: [],
            activeHandleIndex: null,
          },
        },
        highlighted: true,
        isSelected: true,
        isLocked: false,
        isVisible: true,
        invalidated: false,
      };

      const annotationGroupSelector = viewport?.element ?? panelId;
      csAnnotation.state.addAnnotation?.(annotation, annotationGroupSelector);

      contourRep.attachAnnotationUID(segmentationId, segmentIndex, annotationUID);

      segmentationService.setActiveSegmentIndex(segmentationId, segmentIndex);
      segmentationService.activateOnViewport(panelId, segmentationId);
      csAnnotation.selection.setAnnotationSelected?.(annotationUID, true, false);
      csToolUtilities.triggerAnnotationRenderForViewportIds?.([panelId]);
      viewport?.render?.();
      segmentationService.sync();

      return annotationUID;
    },
    closePanel: (panelId: string) => {
      const idx = Number(panelId.split('_')[1]);
      if (!Number.isInteger(idx) || idx <= 0) return false;
      const state = useViewerStore.getState();
      const currentCount = state.layoutConfig.panelCount;
      if (idx >= currentCount) return false;
      const targetLayout = LAYOUT_BY_PANEL_COUNT[idx];
      if (!targetLayout) return false;
      state.setLayout(targetLayout);
      return true;
    },
    getUndoStackInfo,

    // ─── Layout-switching hooks (Signal 6) ───────────────────────
    setLayout: (layout: LayoutType) => {
      useViewerStore.getState().setLayout(layout);
    },
    toggleMpr,
    getDirtyState,
    getSegmentationSnapshot,
    getActiveByPanel,
    exportSegmentationToBase64: async (segmentationId: string) => {
      try {
        return await segmentationService.exportToDicomSeg(segmentationId);
      } catch (err) {
        // Surface the reason on the global so the spec can read it after
        // a null return — silent catch in tests is a footgun.
        (window as unknown as { __XNAT_E2E_LAST_EXPORT_ERROR__?: string }).__XNAT_E2E_LAST_EXPORT_ERROR__ =
          err instanceof Error ? `${err.message}\n${err.stack ?? ''}` : String(err);
        return null;
      }
    },
    markSegmentationDirty: (segmentationId: string) => {
      // Same two writes autoSave.ts:429+434 does on a real edit.
      useSegmentationStore.getState()._markDirty();
      useSegmentationManagerStore.getState().markDirty(segmentationId);
    },
    markAllSegmentationsClean: () => {
      // Mirrors segmentationService.ts:433 (post-save) — clears the
      // global hasUnsavedChanges flag and (via the import-side-effect
      // in _markClean) clears all per-id dirty entries on the manager
      // store.
      useSegmentationStore.getState()._markClean();
    },
    loadLocalDicomFiles: (panelId: string, paths: string[]) =>
      bridgeLoadLocalDicomFiles(panelId, paths),
    setFakeConnected: (connected: boolean) => {
      if (connected) {
        useConnectionStore.setState({
          status: 'connected',
          connection: {
            serverUrl: 'http://e2e-fixture.local',
            username: 'e2e-fixture',
            connectedAt: Date.now(),
          },
          error: null,
        });
      } else {
        useConnectionStore.setState({
          status: 'disconnected',
          connection: null,
          error: null,
        });
      }
    },
    getCrossSeriesAction: (segmentationId: string, viewportId: string) => {
      const eligibility = classifySegmentationOnViewport(segmentationId, viewportId);
      const policy = usePreferencesStore.getState().preferences.multiViewport.crossSeriesRendering;
      const action = resolveAction(eligibility, {
        enabled: policy,
        // Phase 2 ships with a2cOptedIn=false (per-container opt-in lands in
        // Phase 3). Mirror that here so the test sees production behavior.
        a2cOptedIn: false,
      });
      return { eligibility, action };
    },
    getCrossSeriesActionForAnnotation: (annotationUID: string, viewportId: string) => {
      const eligibility = classifyAnnotationOnViewport(annotationUID, viewportId);
      const policy = usePreferencesStore.getState().preferences.multiViewport.crossSeriesRendering;
      const action = resolveAction(eligibility, {
        enabled: policy === 'on',
        a2cOptedIn: false,
      });
      return { eligibility, action };
    },
    getDrawingRoutingDecision: (viewportId: string) => {
      return segmentationService.shouldBlockDrawingOnViewport(viewportId);
    },
    exportRtStructToBase64: async (segmentationId: string) => {
      try {
        return await rtStructService.exportToRtStruct(segmentationId);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.warn('[__XNAT_E2E__] exportRtStructToBase64 failed', msg);
        // Re-throw so the spec sees the actual error rather than `null`.
        // Tests can wrap in try/catch if they need null behavior.
        throw new Error(`exportRtStructToBase64: ${msg}`);
      }
    },
    setMemberRoiType: (memberId: string, roiType: string) => {
      containerService.setRoiType(memberId, roiType as never);
    },
    approveContainer: (containerId: string, by: string | null) => {
      containerService.approveContainer(containerId, by);
    },
    getActiveContainerId: () => {
      return containerBridge.getActiveContainerId();
    },
    getActiveContainerMembers: () => {
      const containerId = containerBridge.getActiveContainerId();
      if (!containerId) return [];
      const container = containerBridge.getContainer(containerId);
      if (!container) return [];
      return container.members.map((m) => ({
        id: m.id,
        segmentIndex: m.segmentIndex,
        roiType: m.roiType,
        provenance: m.provenance,
        name: m.name,
      }));
    },
    installTestSaveAdapter: (saveDelayMs = 50, debounceMs = 25) => {
      // Reset any prior adapter state on re-install (e.g. test re-runs).
      testSaveAdapterStats = {
        saveCount: 0,
        inFlight: 0,
        perContainer: {},
      };
      transport.setAdapter({
        save: async (containerId: string) => {
          testSaveAdapterStats!.saveCount += 1;
          testSaveAdapterStats!.inFlight += 1;
          testSaveAdapterStats!.perContainer[containerId] =
            (testSaveAdapterStats!.perContainer[containerId] ?? 0) + 1;
          await new Promise((resolve) => setTimeout(resolve, saveDelayMs));
          testSaveAdapterStats!.inFlight -= 1;
          // Return `success` so the coordinator clears bridge.dirty.
          return { kind: 'success', token: `test-token-${Date.now()}` } as SaveOutcome;
        },
      });
      transport.setDebounceMs(debounceMs);
      return `test-adapter-${Date.now()}`;
    },
    getTransportTestStats: () => {
      if (!testSaveAdapterStats) return null;
      return {
        saveCount: testSaveAdapterStats.saveCount,
        inFlight: testSaveAdapterStats.inFlight,
        perContainer: { ...testSaveAdapterStats.perContainer },
      };
    },
    transportFlushNow: async (containerId: string) => {
      return transport.flushNow(containerId);
    },
    transportNotifyDirty: (containerId: string) => {
      transport.notifyDirty(containerId);
    },
    waitForTransportIdle: async (containerId: string, timeoutMs = 5_000) => {
      const deadline = Date.now() + timeoutMs;
      while (Date.now() < deadline) {
        const stats = testSaveAdapterStats;
        if (!stats || stats.inFlight === 0) {
          // Also wait one tick so any queued debounce timer flushes.
          await new Promise((resolve) => setTimeout(resolve, 0));
          if (!stats || stats.inFlight === 0) return true;
        }
        await new Promise((resolve) => setTimeout(resolve, 25));
      }
      return false;
    },
    getContainerDirty: (containerId: string) => {
      const c = containerBridge.getContainer(containerId);
      return c ? !!c.dirty : null;
    },
    undoOnce: () => {
      const containerId = containerBridge.getActiveContainerId();
      if (!containerId) return false;
      const entry = undoService.undo(containerId);
      return !!entry;
    },
  };
}
