import { cache, getEnabledElementByViewportId, metaData, utilities as csUtilities } from '@cornerstonejs/core';
import {
  annotation as csAnnotation,
  segmentation as csSegmentation,
  utilities as csToolUtilities,
  PlanarFreehandContourSegmentationTool,
} from '@cornerstonejs/tools';
import { useSegmentationStore } from '../../stores/segmentationStore';
import { useViewerStore } from '../../stores/viewerStore';
import { segmentationManager } from '../segmentation/segmentationManagerSingleton';
import { segmentationService } from '../cornerstone/segmentationService';
import { toolService } from '../cornerstone/toolService';
import { ToolName } from '@shared/types/viewer';

type ActiveSegmentationState = {
  activeSegmentationId: string | null;
  activeSegmentIndex: number;
};

type ActiveContourSnapshot = ActiveSegmentationState & {
  currentImageId: string | null;
  currentSliceIndex: number | null;
  total: number;
  onCurrentSlice: number;
  autoGeneratedTotal: number;
  autoGeneratedOnCurrentSlice: number;
  sliceIndices: number[];
  autoGeneratedSliceIndices: number[];
  selected: string[];
};

let lockAwareUndoRedoCounter = 0;

declare global {
  interface Window {
    __XNAT_E2E__?: {
      getSegmentationCount: () => number;
      getSegmentationIdByLabel: (label: string) => string | null;
      getActiveSegmentationState: () => ActiveSegmentationState;
      getActiveContourSnapshot: (panelId?: string, segmentationId?: string | null) => ActiveContourSnapshot;
      setSelectionTool: () => void;
      activateSegmentation: (panelId: string, segmentationId: string, segmentIndex?: number) => void;
      setSegmentLocked: (segmentationId: string, segmentIndex: number, locked: boolean) => void;
      createLockAwareUndoRedoTestMemo: (segmentationId: string, segmentIndex: number) => boolean;
      getLockAwareUndoRedoCounter: () => number;
      createTestStructure: (panelId: string, label: string) => Promise<string>;
      createTestContour: (panelId: string, segmentationId: string, segmentIndex?: number) => string | null;
    };
  }
}

type Point3 = [number, number, number];

function scalePoint(point: Point3, scalar: number): Point3 {
  return [point[0] * scalar, point[1] * scalar, point[2] * scalar];
}

function addPoint(a: Point3, b: Point3): Point3 {
  return [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
}

function getActiveSegmentationState(): ActiveSegmentationState {
  const state = useSegmentationStore.getState();
  return {
    activeSegmentationId: state.activeSegmentationId,
    activeSegmentIndex: state.activeSegmentIndex,
  };
}

function getActiveContourSnapshot(panelId = 'panel_0', targetSegmentationId?: string | null): ActiveContourSnapshot {
  const { activeSegmentationId, activeSegmentIndex } = getActiveSegmentationState();
  const viewport =
    (getEnabledElementByViewportId(panelId) as {
      viewport?: {
        getCurrentImageId?: () => string | null;
        getCurrentImageIdIndex?: () => number;
      };
    } | undefined)
      ?.viewport
    ?? null;
  const viewerState = useViewerStore.getState();
  const storeSliceIndex = viewerState.viewports[panelId]?.imageIndex;
  const currentSliceIndex = Number.isInteger(viewport?.getCurrentImageIdIndex?.())
    ? Number(viewport?.getCurrentImageIdIndex?.())
    : (Number.isInteger(storeSliceIndex) ? Number(storeSliceIndex) : null);
  const currentImageId =
    viewport?.getCurrentImageId?.()
    ?? (
      currentSliceIndex != null
        ? (viewerState.panelImageIdsMap[panelId] ?? [])[currentSliceIndex] ?? null
        : null
    );
  const allContourAnnotations = csAnnotation.state.getAllAnnotations().filter((annotation: any) => (
    typeof annotation?.metadata?.toolName === 'string'
    && annotation.metadata.toolName.includes('Contour')
  ));
  const selectedAnnotationUIDs = csAnnotation.selection.getAnnotationsSelected?.() ?? [];
  const selectedContourAnnotation = allContourAnnotations.find(
    (annotation: any) => selectedAnnotationUIDs.includes(annotation?.annotationUID),
  );
  const resolvedActiveSegmentationId =
    targetSegmentationId
    ?? activeSegmentationId
    ?? selectedContourAnnotation?.data?.segmentation?.segmentationId
    ?? allContourAnnotations[0]?.data?.segmentation?.segmentationId
    ?? null;
  const resolvedActiveSegmentIndex =
    activeSegmentIndex > 0
      ? activeSegmentIndex
      : Number(selectedContourAnnotation?.data?.segmentation?.segmentIndex ?? 0);

  const contourAnnotations = allContourAnnotations.filter((annotation: any) => (
    annotation?.data?.segmentation?.segmentationId === resolvedActiveSegmentationId
    && typeof annotation?.metadata?.toolName === 'string'
    && annotation.metadata.toolName.includes('Contour')
  ));
  const autoGeneratedAnnotations = contourAnnotations.filter((annotation: any) => annotation?.autoGenerated === true);

  return {
    activeSegmentationId: resolvedActiveSegmentationId,
    activeSegmentIndex: resolvedActiveSegmentIndex,
    currentImageId,
    currentSliceIndex,
    total: contourAnnotations.length,
    onCurrentSlice: contourAnnotations.filter(
      (annotation: any) => annotation?.metadata?.referencedImageId === currentImageId,
    ).length,
    autoGeneratedTotal: autoGeneratedAnnotations.length,
    autoGeneratedOnCurrentSlice: autoGeneratedAnnotations.filter(
      (annotation: any) => annotation?.metadata?.referencedImageId === currentImageId,
    ).length,
    sliceIndices: contourAnnotations
      .map((annotation: any) => annotation?.metadata?.sliceIndex)
      .filter((sliceIndex: unknown): sliceIndex is number => Number.isInteger(sliceIndex))
      .sort((a: number, b: number) => a - b),
    autoGeneratedSliceIndices: autoGeneratedAnnotations
      .map((annotation: any) => annotation?.metadata?.sliceIndex)
      .filter((sliceIndex: unknown): sliceIndex is number => Number.isInteger(sliceIndex))
      .sort((a: number, b: number) => a - b),
    selected: selectedAnnotationUIDs,
  };
}

export function installRendererE2eHooks(): void {
  if (typeof window === 'undefined') {
    return;
  }

  window.__XNAT_E2E__ = {
    getSegmentationCount: () => useSegmentationStore.getState().segmentations.length,
    getSegmentationIdByLabel: (label: string) => (
      useSegmentationStore.getState().segmentations.find((segmentation) => segmentation.label === label)?.segmentationId
      ?? null
    ),
    getActiveSegmentationState,
    getActiveContourSnapshot,
    setSelectionTool: () => {
      toolService.setActiveTool(ToolName.SegmentSelect);
    },
    activateSegmentation: (panelId: string, segmentationId: string, segmentIndex = 1) => {
      useSegmentationStore.getState().setActiveSegmentation(segmentationId);
      segmentationManager.userSelectedSegmentation(panelId, segmentationId, segmentIndex);
    },
    setSegmentLocked: (segmentationId: string, segmentIndex: number, locked: boolean) => {
      const isLocked = segmentationService.getSegmentLocked(segmentationId, segmentIndex);
      if (isLocked !== locked) {
        segmentationService.toggleSegmentLocked(segmentationId, segmentIndex);
      }
    },
    createLockAwareUndoRedoTestMemo: (segmentationId: string, segmentIndex: number) => {
      const historyMemo = (csUtilities as any).HistoryMemo?.DefaultHistoryMemo;
      if (!historyMemo?.push) {
        return false;
      }

      const label =
        useSegmentationStore.getState().segmentations
          .find((segmentation) => segmentation.segmentationId === segmentationId)
          ?.segments.find((segment) => segment.segmentIndex === segmentIndex)
          ?.label
        ?? `Segment ${segmentIndex}`;

      lockAwareUndoRedoCounter = 0;
      historyMemo.push({
        id: `e2e-history-${segmentationId}-${segmentIndex}`,
        operationType: 'annotation',
        segmentationId,
        segmentIndex,
        label,
        restoreMemo: () => {
          lockAwareUndoRedoCounter += 1;
        },
      });
      return true;
    },
    getLockAwareUndoRedoCounter: () => lockAwareUndoRedoCounter,
    createTestStructure: async (panelId: string, label: string) => {
      const sourceImageIds = useViewerStore.getState().panelImageIdsMap[panelId] ?? [];
      if (sourceImageIds.length === 0) {
        throw new Error(`No source images available for ${panelId}`);
      }

      const segmentationId = await segmentationManager.createNewStructure(panelId, sourceImageIds, label);
      const segmentIndex = await segmentationManager.addSegment(segmentationId, `${label} Segment`);
      useSegmentationStore.getState().setActiveSegmentation(segmentationId);
      segmentationManager.userSelectedSegmentation(panelId, segmentationId, segmentIndex);
      return segmentationId;
    },
    createTestContour: (panelId: string, segmentationId: string, segmentIndex = 1) => {
      const enabledElement = getEnabledElementByViewportId(panelId) as
        | {
            viewport?: {
              getCurrentImageId?: () => string | null;
              getCurrentImageIdIndex?: () => number;
              getViewReference?: (options?: { sliceIndex?: number }) => Record<string, unknown> | undefined;
              getCamera?: () => { viewPlaneNormal?: unknown; viewUp?: unknown } | undefined;
              canvasToWorld?: (point: [number, number]) => Point3;
              render?: () => void;
            };
          }
        | undefined;
      const viewport = enabledElement?.viewport;
      const viewerState = useViewerStore.getState();
      const storeSliceIndex = viewerState.viewports[panelId]?.imageIndex;
      const currentSliceIndex = Number.isInteger(viewport?.getCurrentImageIdIndex?.())
        ? Number(viewport?.getCurrentImageIdIndex?.())
        : (Number.isInteger(storeSliceIndex) ? Number(storeSliceIndex) : null);
      const viewReference = currentSliceIndex != null
        ? viewport?.getViewReference?.({ sliceIndex: currentSliceIndex })
        : viewport?.getViewReference?.();
      const camera = viewport?.getCamera?.();
      const viewPlaneNormal = Array.isArray((viewReference as { viewPlaneNormal?: unknown } | undefined)?.viewPlaneNormal)
        ? (viewReference as { viewPlaneNormal: Point3 }).viewPlaneNormal
        : (Array.isArray(camera?.viewPlaneNormal) ? camera.viewPlaneNormal as Point3 : undefined);
      const viewUp = Array.isArray((viewReference as { viewUp?: unknown } | undefined)?.viewUp)
        ? (viewReference as { viewUp: Point3 }).viewUp
        : (Array.isArray(camera?.viewUp) ? camera.viewUp as Point3 : undefined);
      const currentImageId =
        viewport?.getCurrentImageId?.()
        ?? (() => {
          const imageIds = viewerState.panelImageIdsMap[panelId] ?? [];
          const imageIndex = viewerState.viewports[panelId]?.imageIndex ?? 0;
          return imageIds[imageIndex] ?? null;
        })();
      if (!currentImageId) return null;

      const canvas = document.querySelector(
        `[data-testid="cornerstone-viewport-canvas:${panelId}"] canvas`,
      ) as HTMLCanvasElement | null;

      if (canvas && typeof viewport?.canvasToWorld === 'function') {
        const width = canvas.clientWidth || canvas.width || 0;
        const height = canvas.clientHeight || canvas.height || 0;
        if (width > 0 && height > 0) {
          const points: Point3[] = [
            viewport.canvasToWorld([width * 0.38, height * 0.38]),
            viewport.canvasToWorld([width * 0.54, height * 0.38]),
            viewport.canvasToWorld([width * 0.54, height * 0.54]),
            viewport.canvasToWorld([width * 0.38, height * 0.54]),
          ];
          if (points.every(Boolean)) {
            const annotationUID = csUtilities.uuidv4();
            const annotation: any = {
              annotationUID,
              metadata: {
                toolName: PlanarFreehandContourSegmentationTool.toolName,
                referencedImageId: currentImageId,
                FrameOfReferenceUID: metaData.get('imagePlaneModule', currentImageId)?.frameOfReferenceUID,
                sliceIndex: currentSliceIndex ?? undefined,
                viewPlaneNormal,
                viewUp,
              },
              data: {
                contour: {
                  polyline: points,
                  closed: true,
                },
                segmentation: {
                  segmentationId,
                  segmentIndex,
                },
                handles: {
                  points: [],
                  activeHandleIndex: null,
                },
              },
              highlighted: true,
              isSelected: true,
              isLocked: false,
              isVisible: true,
              invalidated: false,
            };

            const annotationGroupSelector = viewport?.element ?? panelId;
            csAnnotation.state.addAnnotation?.(annotation, annotationGroupSelector);
            const segmentation = csSegmentation.state.getSegmentation(segmentationId);
            const contourData = (segmentation?.representationData as any)?.Contour;
            if (contourData?.annotationUIDsMap instanceof Map) {
              if (!contourData.annotationUIDsMap.has(segmentIndex)) {
                contourData.annotationUIDsMap.set(segmentIndex, new Set<string>());
              }
              contourData.annotationUIDsMap.get(segmentIndex)?.add(annotationUID);
            }

            segmentationService.setActiveSegmentIndex(segmentationId, segmentIndex);
            segmentationService.activateOnViewport(panelId, segmentationId);
            csAnnotation.selection.setAnnotationSelected?.(annotationUID, true, false);
            csToolUtilities.triggerAnnotationRenderForViewportIds?.([panelId]);
            viewport.render?.();
            segmentationService.sync();

            return annotationUID;
          }
        }
      }

      const plane = metaData.get('imagePlaneModule', currentImageId) as
        | {
            imagePositionPatient?: Point3;
            rowCosines?: Point3;
            columnCosines?: Point3;
            frameOfReferenceUID?: string;
            rowPixelSpacing?: number;
            columnPixelSpacing?: number;
          }
        | undefined;
      const image = cache.getImage(currentImageId) as
        | {
            rows?: number;
            columns?: number;
            rowPixelSpacing?: number;
            columnPixelSpacing?: number;
          }
        | undefined;
      if (!plane?.imagePositionPatient || !plane.rowCosines || !plane.columnCosines) {
        return null;
      }

      const rowSpacing = Number(plane.rowPixelSpacing ?? image?.rowPixelSpacing ?? 1);
      const columnSpacing = Number(plane.columnPixelSpacing ?? image?.columnPixelSpacing ?? 1);
      const rows = Number(image?.rows ?? 256);
      const columns = Number(image?.columns ?? 256);

      const rowAxis = plane.rowCosines;
      const columnAxis = plane.columnCosines;
      const origin = plane.imagePositionPatient;
      const center = addPoint(
        addPoint(origin, scalePoint(rowAxis, columns * columnSpacing * 0.45)),
        scalePoint(columnAxis, rows * rowSpacing * 0.45),
      );
      const size = Math.max(6, Math.min(rows * rowSpacing, columns * columnSpacing) * 0.06);

      const points: Point3[] = [
        addPoint(addPoint(center, scalePoint(rowAxis, -size)), scalePoint(columnAxis, -size)),
        addPoint(addPoint(center, scalePoint(rowAxis, size)), scalePoint(columnAxis, -size)),
        addPoint(addPoint(center, scalePoint(rowAxis, size)), scalePoint(columnAxis, size)),
        addPoint(addPoint(center, scalePoint(rowAxis, -size)), scalePoint(columnAxis, size)),
      ];

      const annotationUID = csUtilities.uuidv4();
      const annotation: any = {
        annotationUID,
        metadata: {
          toolName: PlanarFreehandContourSegmentationTool.toolName,
          referencedImageId: currentImageId,
          FrameOfReferenceUID: plane.frameOfReferenceUID,
          sliceIndex: currentSliceIndex ?? undefined,
          viewPlaneNormal,
          viewUp,
        },
        data: {
          contour: {
            polyline: points,
            closed: true,
          },
          segmentation: {
            segmentationId,
            segmentIndex,
          },
          handles: {
            points: [],
            activeHandleIndex: null,
          },
        },
        highlighted: true,
        isSelected: true,
        isLocked: false,
        isVisible: true,
        invalidated: false,
      };

      const annotationGroupSelector = viewport?.element ?? panelId;
      csAnnotation.state.addAnnotation?.(annotation, annotationGroupSelector);

      const segmentation = csSegmentation.state.getSegmentation(segmentationId);
      const contourData = (segmentation?.representationData as any)?.Contour;
      if (contourData?.annotationUIDsMap instanceof Map) {
        if (!contourData.annotationUIDsMap.has(segmentIndex)) {
          contourData.annotationUIDsMap.set(segmentIndex, new Set<string>());
        }
        contourData.annotationUIDsMap.get(segmentIndex)?.add(annotationUID);
      }

      segmentationService.setActiveSegmentIndex(segmentationId, segmentIndex);
      segmentationService.activateOnViewport(panelId, segmentationId);
      csAnnotation.selection.setAnnotationSelected?.(annotationUID, true, false);
      csToolUtilities.triggerAnnotationRenderForViewportIds?.([panelId]);
      viewport?.render?.();
      segmentationService.sync();

      return annotationUID;
    },
  };
}
