/**
 * Keep the annotation selection on a contour stroke after Cornerstone 5 replaces it.
 *
 * On v5 every finished contour-segmentation stroke goes through the contour union
 * (`contourSegmentationCompleted` → `addContourStroke`): the stroke and every same-plane
 * contour of its segment are removed and the result is added as NEW annotations, with
 * new UIDs — even when there was nothing to union with. Removing an annotation does not
 * deselect it, so the selection is left holding the UID of the stroke, which no longer
 * exists. Everything that acts on "the selected contour" (Ctrl+C, delete) then silently
 * does nothing.
 *
 * The union also removes and re-creates every OTHER contour of that segment on the plane,
 * so a selected neighbour loses its UID too (e.g. the first of several pasted contours).
 * So when the union completes, every selected contour it replaced moves to the result
 * that contains it. A union result always contains what it merged; a separate contour of
 * the segment cannot, or the two would have been merged. A contour no result contains (a
 * hole cut, where the stroke is subtracted) is simply dropped.
 */
import { eventTarget } from '@cornerstonejs/core';
import { annotation as csAnnotation, Enums as ToolEnums } from '@cornerstonejs/tools';
import { isContourSegmentationAnnotation } from './contourRepresentation';

interface StrokeAnnotation {
  annotationUID?: string;
  parentAnnotationUID?: string;
  autoGenerated?: boolean;
  metadata?: { referencedImageId?: string };
  data?: {
    contour?: { polyline?: ArrayLike<number>[] };
    segmentation?: { segmentationId?: string; segmentIndex?: number };
  };
}

/** World-space tolerance (mm) for "contains" — the union re-samples the outline. */
const CONTAIN_EPSILON = 1e-3;

/** Contours added during the current synchronous task — the union adds its results
 *  synchronously, right before it signals completion. */
let addedThisTask: StrokeAnnotation[] = [];
let clearScheduled = false;
let installed = false;

/** Contours added / removed during the current synchronous task — the union removes the
 *  stroke and every same-plane contour of its segment, then adds the results, all
 *  synchronously, right before it signals completion. */
let removedThisTask: StrokeAnnotation[] = [];

function trackThisTask(list: 'added' | 'removed', annotation: StrokeAnnotation): void {
  if (list === 'added') addedThisTask.push(annotation);
  else removedThisTask.push(annotation);
  if (!clearScheduled) {
    clearScheduled = true;
    queueMicrotask(() => {
      addedThisTask = [];
      removedThisTask = [];
      clearScheduled = false;
    });
  }
}

function onAnnotationAdded(evt: Event): void {
  const annotation = (evt as CustomEvent<{ annotation?: unknown }>).detail?.annotation;
  if (isContourSegmentationAnnotation(annotation)) trackThisTask('added', annotation as StrokeAnnotation);
}

function onAnnotationRemoved(evt: Event): void {
  const annotation = (evt as CustomEvent<{ annotation?: unknown }>).detail?.annotation;
  if (isContourSegmentationAnnotation(annotation)) trackThisTask('removed', annotation as StrokeAnnotation);
}

function bounds(annotation: StrokeAnnotation): { min: number[]; max: number[] } | null {
  const polyline = annotation.data?.contour?.polyline;
  if (!polyline || polyline.length === 0) return null;
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];
  for (const point of polyline) {
    for (let axis = 0; axis < 3; axis++) {
      min[axis] = Math.min(min[axis], point[axis]);
      max[axis] = Math.max(max[axis], point[axis]);
    }
  }
  return { min, max };
}

function contains(outer: StrokeAnnotation, inner: StrokeAnnotation): boolean {
  const o = bounds(outer);
  const i = bounds(inner);
  if (!o || !i) return false;
  for (let axis = 0; axis < 3; axis++) {
    if (i.min[axis] < o.min[axis] - CONTAIN_EPSILON) return false;
    if (i.max[axis] > o.max[axis] + CONTAIN_EPSILON) return false;
  }
  return true;
}

/** The union result that took a removed contour's place: same segment and slice, and it
 *  contains the removed contour (a union only grows what it merged). */
function resultFor(removed: StrokeAnnotation): string | null {
  const seg = removed.data?.segmentation;
  const result = addedThisTask.find(
    (candidate) =>
      candidate.annotationUID !== removed.annotationUID
      && !candidate.parentAnnotationUID
      && !candidate.autoGenerated
      && candidate.data?.segmentation?.segmentationId === seg?.segmentationId
      && Number(candidate.data?.segmentation?.segmentIndex) === Number(seg?.segmentIndex)
      && candidate.metadata?.referencedImageId === removed.metadata?.referencedImageId
      && !!candidate.annotationUID
      && !!csAnnotation.state.getAnnotation?.(candidate.annotationUID)
      && contains(candidate, removed),
  );
  return result?.annotationUID ?? null;
}

function onCutMergeCompleted(): void {
  const selected = csAnnotation.selection.getAnnotationsSelected?.() ?? [];
  if (selected.length === 0) return;
  // Every selected contour the union replaced — the stroke itself, or an earlier contour
  // of the segment it was merged with or merely re-created beside — is swapped for the
  // result that took its place; one that was cut away (a hole) is dropped.
  let changed = false;
  const next: string[] = [];
  for (const uid of selected) {
    if (csAnnotation.state.getAnnotation?.(uid)) {
      if (!next.includes(uid)) next.push(uid);
      continue;
    }
    changed = true;
    const removed = removedThisTask.find((a) => a.annotationUID === uid);
    const replacement = removed ? resultFor(removed) : null;
    if (replacement && !next.includes(replacement)) next.push(replacement);
  }
  if (!changed) return;
  // Cornerstone's single-UID deselect writes `isSelected` on the annotation and throws
  // once it is gone, so clear the set (which tolerates missing annotations) and re-select.
  csAnnotation.selection.deselectAnnotation?.();
  next.forEach((uid, i) => csAnnotation.selection.setAnnotationSelected?.(uid, true, i > 0));
}

/** Install once, at init. */
export function installContourStrokeSelection(): void {
  if (installed) return;
  installed = true;
  eventTarget.addEventListener(ToolEnums.Events.ANNOTATION_ADDED, onAnnotationAdded);
  eventTarget.addEventListener(ToolEnums.Events.ANNOTATION_REMOVED, onAnnotationRemoved);
  eventTarget.addEventListener(ToolEnums.Events.ANNOTATION_CUT_MERGE_PROCESS_COMPLETED, onCutMergeCompleted);
}
