/**
 * Keep the annotation selection on a contour stroke after Cornerstone 5 replaces it.
 *
 * On v5 every finished contour-segmentation stroke goes through the contour union
 * (`contourSegmentationCompleted` → `addContourStroke`): the stroke and every same-plane
 * contour of its segment are removed and the result is added as NEW annotations, with
 * new UIDs — even when there was nothing to union with. Removing an annotation does not
 * deselect it, so the selection is left holding the UID of the stroke, which no longer
 * exists. Everything that acts on "the selected contour" (Ctrl+C, delete) then silently
 * does nothing.
 *
 * So when the union completes for a selected stroke, the selection moves to the result
 * contour that contains it. A union result always contains the whole stroke; a separate
 * contour of the segment cannot, or the two would have been merged. If no result
 * contains it (a hole cut, where the stroke is subtracted), the stale UID is simply
 * dropped.
 */
import { eventTarget } from '@cornerstonejs/core';
import { annotation as csAnnotation, Enums as ToolEnums } from '@cornerstonejs/tools';
import { isContourSegmentationAnnotation } from './contourRepresentation';

interface StrokeAnnotation {
  annotationUID?: string;
  parentAnnotationUID?: string;
  autoGenerated?: boolean;
  metadata?: { referencedImageId?: string };
  data?: {
    contour?: { polyline?: ArrayLike<number>[] };
    segmentation?: { segmentationId?: string; segmentIndex?: number };
  };
}

/** World-space tolerance (mm) for "contains" — the union re-samples the outline. */
const CONTAIN_EPSILON = 1e-3;

/** Contours added during the current synchronous task — the union adds its results
 *  synchronously, right before it signals completion. */
let addedThisTask: StrokeAnnotation[] = [];
let clearScheduled = false;
let installed = false;

function onAnnotationAdded(evt: Event): void {
  const annotation = (evt as CustomEvent<{ annotation?: unknown }>).detail?.annotation;
  if (!isContourSegmentationAnnotation(annotation)) return;
  addedThisTask.push(annotation as StrokeAnnotation);
  if (!clearScheduled) {
    clearScheduled = true;
    queueMicrotask(() => {
      addedThisTask = [];
      clearScheduled = false;
    });
  }
}

function bounds(annotation: StrokeAnnotation): { min: number[]; max: number[] } | null {
  const polyline = annotation.data?.contour?.polyline;
  if (!polyline || polyline.length === 0) return null;
  const min = [Infinity, Infinity, Infinity];
  const max = [-Infinity, -Infinity, -Infinity];
  for (const point of polyline) {
    for (let axis = 0; axis < 3; axis++) {
      min[axis] = Math.min(min[axis], point[axis]);
      max[axis] = Math.max(max[axis], point[axis]);
    }
  }
  return { min, max };
}

function contains(outer: StrokeAnnotation, inner: StrokeAnnotation): boolean {
  const o = bounds(outer);
  const i = bounds(inner);
  if (!o || !i) return false;
  for (let axis = 0; axis < 3; axis++) {
    if (i.min[axis] < o.min[axis] - CONTAIN_EPSILON) return false;
    if (i.max[axis] > o.max[axis] + CONTAIN_EPSILON) return false;
  }
  return true;
}

function onCutMergeCompleted(evt: Event): void {
  const source = (evt as CustomEvent<{ sourceAnnotation?: StrokeAnnotation }>).detail?.sourceAnnotation;
  const sourceUID = source?.annotationUID;
  if (!source || !sourceUID) return;
  const selected = csAnnotation.selection.getAnnotationsSelected?.() ?? [];
  if (!selected.includes(sourceUID)) return;
  if (csAnnotation.state.getAnnotation?.(sourceUID)) return; // not replaced

  const seg = source.data?.segmentation;
  const result = addedThisTask.find(
    (candidate) =>
      candidate.annotationUID !== sourceUID
      && !candidate.parentAnnotationUID
      && !candidate.autoGenerated
      && candidate.data?.segmentation?.segmentationId === seg?.segmentationId
      && Number(candidate.data?.segmentation?.segmentIndex) === Number(seg?.segmentIndex)
      && candidate.metadata?.referencedImageId === source.metadata?.referencedImageId
      && !!candidate.annotationUID
      && !!csAnnotation.state.getAnnotation?.(candidate.annotationUID)
      && contains(candidate, source),
  );

  if (result?.annotationUID) {
    // Replaces the whole selection, dropping the stale UID with it.
    csAnnotation.selection.setAnnotationSelected?.(result.annotationUID, true, false);
  } else {
    csAnnotation.selection.deselectAnnotation?.(sourceUID);
  }
}

/** Install once, at init. */
export function installContourStrokeSelection(): void {
  if (installed) return;
  installed = true;
  eventTarget.addEventListener(ToolEnums.Events.ANNOTATION_ADDED, onAnnotationAdded);
  eventTarget.addEventListener(ToolEnums.Events.ANNOTATION_CUT_MERGE_PROCESS_COMPLETED, onCutMergeCompleted);
}
