/**
 * Interpolation acceptance — promote auto-generated interpolated contours
 * to "accepted" state so they are saved with the RTSTRUCT.
 *
 * Background: Cornerstone3D's contour-interpolation machinery creates
 * intermediate contour annotations with `autoGenerated: true`. These
 * render as dashed outlines and are NOT registered in the segmentation's
 * `annotationUIDsMap`, so `generateRTSSFromContour` (which iterates that
 * map) excludes them from the written RTSTRUCT. Until a contour is
 * "accepted" it is provisional and saveless.
 *
 * This module exposes the accept primitive plus two event-driven policies:
 *
 *   1. Auto-accept on generation (preference-gated). Subscribes to
 *      `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED` and, when the
 *      `autoAcceptInterpolated` preference is true, promotes every
 *      auto-generated contour in the event's viewport.
 *
 *   2. Click-to-accept. Subscribes to `ANNOTATION_SELECTION_CHANGE`.
 *      If the user selected an auto-generated annotation, accept just
 *      that one. Works regardless of the preference — when the
 *      preference is true, the contour is already accepted at generation
 *      time so this is a no-op; when false, it's how the user promotes
 *      individual contours.
 *
 * Acceptance primitive (`acceptAnnotation`) mirrors what Cornerstone's
 * `InterpolationManager.acceptAutoGenerated` does per annotation:
 *   - Register the UID in the segmentation's `annotationUIDsMap`
 *     (via `contourRep.addAnnotation`).
 *   - Clear `autoGenerated` so the renderer switches from dashed to solid.
 */
import { eventTarget } from '@cornerstonejs/core';
import {
  annotation as csAnnotation,
  Enums as ToolEnums,
} from '@cornerstonejs/tools';
import * as contourRep from './contourRepresentation';
import { usePreferencesStore } from '../../stores/preferencesStore';

const Events = ToolEnums.Events as Record<string, string>;

/**
 * Promote one auto-generated contour annotation to "accepted":
 *   - adds its UID to the segmentation's annotationUIDsMap
 *   - flips `autoGenerated` to false (→ solid render)
 *
 * No-op if the annotation is already accepted (autoGenerated !== true).
 * Returns true if the annotation was actually promoted.
 */
export function acceptAnnotation(annotation: unknown): boolean {
  const ann = annotation as { autoGenerated?: boolean } | undefined;
  if (!ann || ann.autoGenerated !== true) return false;

  const added = contourRep.addAnnotation(annotation as any);
  if (!added) return false;

  ann.autoGenerated = false;
  return true;
}

/**
 * Iterate Cornerstone's global annotation state and return auto-generated
 * contour annotations whose segmentation matches the given ID.
 */
function collectAutoGeneratedForSegmentation(segmentationId: string): any[] {
  const all = csAnnotation.state.getAllAnnotations?.() ?? [];
  const out: any[] = [];
  for (const ann of all) {
    if ((ann as any)?.autoGenerated !== true) continue;
    const segId = (ann as any)?.data?.segmentation?.segmentationId;
    if (segId !== segmentationId) continue;
    out.push(ann);
  }
  return out;
}

/**
 * How many auto-generated (unaccepted) contours exist for this
 * segmentation. Used to decide whether to prompt at manual-save time.
 */
export function countAutoGeneratedForSegmentation(segmentationId: string): number {
  return collectAutoGeneratedForSegmentation(segmentationId).length;
}

/**
 * Accept every auto-generated contour for a given segmentation. Returns
 * the number of contours that were promoted. Used by the manual-save
 * "accept all & save" flow.
 */
export function acceptAllForSegmentation(segmentationId: string): number {
  const pending = collectAutoGeneratedForSegmentation(segmentationId);
  let accepted = 0;
  for (const ann of pending) {
    if (acceptAnnotation(ann)) accepted++;
  }
  return accepted;
}

// ─── Event-driven policies ────────────────────────────────────────

/**
 * Auto-accept-on-generation handler. Scans current annotation state
 * (rather than trusting the event detail shape) and promotes every
 * auto-generated contour. Cheap because there are at most a few
 * interpolated contours per generation pass.
 */
function onInterpolationProcessCompleted(): void {
  const autoAccept = usePreferencesStore.getState().preferences.interpolation.autoAcceptInterpolated;
  if (!autoAccept) return;

  const all = csAnnotation.state.getAllAnnotations?.() ?? [];
  for (const ann of all) {
    if ((ann as any)?.autoGenerated === true) {
      acceptAnnotation(ann);
    }
  }
}

/**
 * Click-to-accept handler. Fires on ANNOTATION_SELECTION_CHANGE. If the
 * newly-selected annotation is auto-generated, accept it. Independent of
 * the preference — when the preference is on, auto-generated contours
 * are already accepted and this is a no-op.
 */
function onAnnotationSelectionChange(evt: Event): void {
  const detail = (evt as CustomEvent<{ selection?: string[] }>).detail;
  const selection = Array.isArray(detail?.selection) ? detail.selection : [];
  if (selection.length === 0) return;

  // Accept every auto-generated annotation in the new selection. In
  // practice the selection is usually one UID (the one the user clicked),
  // but iterating is safer than assuming.
  for (const annotationUID of selection) {
    const ann = csAnnotation.state.getAnnotation?.(annotationUID);
    if (!ann) continue;
    acceptAnnotation(ann);
  }
}

// ─── Listener lifecycle ───────────────────────────────────────────

let initialized = false;

export function initialize(): void {
  if (initialized) return;

  // `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED` is emitted by Cornerstone
  // after `interpolate()` finishes generating contours for a gap.
  const interpolationCompletedType = Events.ANNOTATION_INTERPOLATION_PROCESS_COMPLETED;
  if (interpolationCompletedType) {
    eventTarget.addEventListener(interpolationCompletedType, onInterpolationProcessCompleted);
  }
  eventTarget.addEventListener(Events.ANNOTATION_SELECTION_CHANGE, onAnnotationSelectionChange as EventListener);

  initialized = true;
}

export function dispose(): void {
  if (!initialized) return;
  const interpolationCompletedType = Events.ANNOTATION_INTERPOLATION_PROCESS_COMPLETED;
  if (interpolationCompletedType) {
    eventTarget.removeEventListener(interpolationCompletedType, onInterpolationProcessCompleted);
  }
  eventTarget.removeEventListener(Events.ANNOTATION_SELECTION_CHANGE, onAnnotationSelectionChange as EventListener);
  initialized = false;
}
