/**
 * Auto-accept on interpolation completion.
 *
 * MV-Phase 4.6 (write-through model — design §B5). Cornerstone3D's
 * interpolate() generates contour annotations with `autoGenerated: true`
 * that are NOT registered in the segmentation's `annotationUIDsMap`,
 * so `generateRTSSFromContour` (which iterates that map) excludes them
 * from any RTSTRUCT export.
 *
 * Per design §B5 the interpolated geometry is **always** committed at
 * the moment of interpolation — there is no per-contour click-to-promote
 * gate, no preference toggle, no save-time dialog. This module
 * implements the always-accept policy:
 *
 *   1. Subscribe to `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED`.
 *   2. Walk the global annotation state for every `autoGenerated` entry.
 *   3. Register each in its segmentation's `annotationUIDsMap` (via
 *      `contourRep.addAnnotation`) and flip `autoGenerated` to false so
 *      the renderer switches from dashed to solid.
 *
 * Replaces the legacy `interpolationAcceptance.ts` (deleted in 4.6) and
 * its preference-gated / click-to-accept policies.
 */
import { eventTarget } from '@cornerstonejs/core';
import {
  annotation as csAnnotation,
  Enums as ToolEnums,
} from '@cornerstonejs/tools';
import * as contourRep from '../contourRepresentation';

const Events = ToolEnums.Events as Record<string, string>;

/**
 * Promote one auto-generated contour annotation:
 *   - adds its UID to the segmentation's annotationUIDsMap;
 *   - flips `autoGenerated` to false (→ solid render).
 *
 * No-op if the annotation is already accepted (autoGenerated !== true).
 * Returns true when the annotation was actually promoted.
 */
export function acceptAnnotation(annotation: unknown): boolean {
  const ann = annotation as { autoGenerated?: boolean } | undefined;
  if (!ann || ann.autoGenerated !== true) return false;

  const added = contourRep.addAnnotation(annotation as any);
  if (!added) return false;

  ann.autoGenerated = false;
  return true;
}

/**
 * Walk Cornerstone's global annotation state and accept every entry
 * with `autoGenerated === true`. Cheap because Cornerstone fires the
 * completion event once per pass; at most a few interpolated contours
 * exist in flight at any moment.
 */
function onInterpolationProcessCompleted(): void {
  const all = csAnnotation.state.getAllAnnotations?.() ?? [];
  for (const ann of all) {
    if ((ann as any)?.autoGenerated === true) {
      acceptAnnotation(ann);
    }
  }
}

// ─── Listener lifecycle ───────────────────────────────────────────────

let initialized = false;
let listener: EventListener | null = null;

export function initialize(): void {
  if (initialized) return;
  const eventName = Events.ANNOTATION_INTERPOLATION_PROCESS_COMPLETED;
  if (!eventName) return;

  listener = onInterpolationProcessCompleted as EventListener;
  eventTarget.addEventListener(eventName, listener);
  initialized = true;
}

export function dispose(): void {
  if (!initialized) return;
  const eventName = Events.ANNOTATION_INTERPOLATION_PROCESS_COMPLETED;
  if (eventName && listener) {
    eventTarget.removeEventListener(eventName, listener);
  }
  listener = null;
  initialized = false;
}
