/**
 * Inter-slice interpolation: single-undo-entry batching.
 *
 * MV-Phase 4.3. Per design §B5 and requirement A8: "one interpolation
 * operation across N slices = one entry — interpolated contours undo
 * as a group."
 *
 * Mechanism:
 *   1. `historyMemo.routeMemoToUndoService` diverts memos for
 *      `autoGenerated` annotations into a per-container buffer (gated
 *      on `multiViewport.enabled` so flag-off legacy behavior is
 *      unchanged).
 *   2. Cornerstone fires `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED`
 *      after `interpolate()` finishes a pass.
 *   3. This module drains the buffer for the affected container and
 *      records a single batched `HistoryEntry` whose apply/invert
 *      replays each buffered entry's apply/invert in stack order.
 *
 * Apply order is oldest-first (mirrors the order Cornerstone created the
 * contours during the interpolation pass). Invert order is newest-first
 * (each individual invert undoes the corresponding apply, so reversing
 * the iteration order is required for correctness — same convention
 * any transactional rollback uses).
 *
 * DI pattern matches `provenance.ts` so tests pass synthetic deps.
 */
import { eventTarget } from '@cornerstonejs/core';
import { Enums as ToolEnums } from '@cornerstonejs/tools';
import type { HistoryEntry } from '../../../types/annotation';

// ─── DI seam ──────────────────────────────────────────────────────────

export interface InterpolationUndoDeps {
  /**
   * Resolve a Cornerstone segmentationId to a containerId, or null if
   * the segmentation isn't tracked by the bridge. Used to scope the
   * buffer drain.
   */
  getContainerId: (csSegmentationId: string) => string | null;

  /** Take and return the buffered auto-generated entries for a container. */
  takeAutoGeneratedBuffer: (containerId: string) => HistoryEntry[];

  /** Push the merged HistoryEntry to undoService. */
  recordEntry: (containerId: string, entry: HistoryEntry) => void;
}

// ─── Pure handler ─────────────────────────────────────────────────────

/**
 * Process one `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED` event detail.
 * Pure — takes the detail and the deps, returns the number of entries
 * merged (0 if no buffer for the container or detail was malformed).
 */
export function handleInterpolationCompleted(
  detail: unknown,
  deps: InterpolationUndoDeps,
): number {
  const segId = readSegmentationId(detail);
  if (typeof segId !== 'string' || segId.length === 0) return 0;
  const containerId = deps.getContainerId(segId);
  if (!containerId) return 0;
  const buffered = deps.takeAutoGeneratedBuffer(containerId);
  if (buffered.length === 0) return 0;

  const merged = mergeEntries(buffered);
  deps.recordEntry(containerId, merged);
  return buffered.length;
}

/**
 * Build a single HistoryEntry that replays all buffered entries.
 *
 * `apply` runs each entry's apply in stack order (oldest first).
 * `invert` runs each entry's invert in REVERSE stack order (newest
 * first), so the state unwinds correctly.
 *
 * `scopeMemberIds` is the union of the merged entries' scopes (no
 * duplicates).
 */
export function mergeEntries(entries: HistoryEntry[]): HistoryEntry {
  const scopeMembers = new Set<string>();
  for (const e of entries) {
    for (const m of e.scopeMemberIds) scopeMembers.add(m);
  }
  return {
    description:
      entries.length === 1
        ? entries[0].description
        : `Interpolate ${entries.length} contours`,
    apply: () => {
      for (const e of entries) {
        try {
          e.apply();
        } catch (err) {
          console.warn('[interpolationUndo] apply failed', err);
        }
      }
    },
    invert: () => {
      for (let i = entries.length - 1; i >= 0; i--) {
        try {
          entries[i].invert();
        } catch (err) {
          console.warn('[interpolationUndo] invert failed', err);
        }
      }
    },
    scopeMemberIds: Array.from(scopeMembers),
    at: Date.now(),
  };
}

function readSegmentationId(detail: unknown): string | undefined {
  const annotation = (detail as { annotation?: unknown } | undefined)?.annotation;
  const data = (annotation as { data?: unknown } | undefined)?.data;
  const segmentation = (data as { segmentation?: { segmentationId?: string } } | undefined)
    ?.segmentation;
  return typeof segmentation?.segmentationId === 'string'
    ? segmentation.segmentationId
    : undefined;
}

// ─── Listener lifecycle ───────────────────────────────────────────────

const NOOP_DEPS: InterpolationUndoDeps = {
  getContainerId: () => null,
  takeAutoGeneratedBuffer: () => [],
  recordEntry: () => undefined,
};

let deps: InterpolationUndoDeps = NOOP_DEPS;
let initialized = false;
let onInterpolationCompleted: EventListener | null = null;

/** Inject the production deps. Called from `segmentationService.initialize()`. */
export function wireInterpolationUndo(injected: Partial<InterpolationUndoDeps>): void {
  deps = { ...NOOP_DEPS, ...injected };
}

/** Reset deps to no-op stubs. Used by test teardown. */
export function resetInterpolationUndoWiring(): void {
  deps = NOOP_DEPS;
}

/** Subscribe to `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED`. Idempotent. */
export function initialize(): void {
  if (initialized) return;

  onInterpolationCompleted = (evt: Event) => {
    const detail = (evt as CustomEvent<unknown>).detail;
    try {
      handleInterpolationCompleted(detail, deps);
    } catch (err) {
      // Same dispatcher-protection rationale as provenance.ts: a throw
      // here would leak a buffer of un-merged entries forward; the
      // user-visible effect would be a glitchy undo stack on the next
      // pass. Better to swallow + warn.
      console.warn('[interpolationUndo] batch failed', err);
    }
  };

  const eventName = (ToolEnums.Events as Record<string, string>)
    .ANNOTATION_INTERPOLATION_PROCESS_COMPLETED;
  if (eventName) {
    eventTarget.addEventListener(eventName, onInterpolationCompleted);
  }

  initialized = true;
}

/** Tear down the listener. Idempotent. */
export function dispose(): void {
  if (!initialized) return;
  const eventName = (ToolEnums.Events as Record<string, string>)
    .ANNOTATION_INTERPOLATION_PROCESS_COMPLETED;
  if (eventName && onInterpolationCompleted) {
    eventTarget.removeEventListener(eventName, onInterpolationCompleted);
  }
  onInterpolationCompleted = null;
  initialized = false;
}
