/**
 * Tests for the Phase 4.3 interpolationUndo module.
 *
 * Pure-handler tests exercise `handleInterpolationCompleted` with
 * synthetic deps. Lifecycle tests dispatch through the mock event
 * target. `mergeEntries` is tested in isolation for apply/invert order
 * and scope-union semantics.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const { mockEventTarget } = vi.hoisted(() => ({
  mockEventTarget: new EventTarget(),
}));

vi.mock('@cornerstonejs/core', () => ({
  eventTarget: mockEventTarget,
}));

vi.mock('@cornerstonejs/tools', () => ({
  Enums: {
    Events: {
      ANNOTATION_INTERPOLATION_PROCESS_COMPLETED:
        'CS_TOOLS_ANNOTATION_INTERPOLATION_PROCESS_COMPLETED',
    },
  },
}));

import {
  dispose,
  handleInterpolationCompleted,
  initialize,
  mergeEntries,
  resetInterpolationUndoWiring,
  wireInterpolationUndo,
  type InterpolationUndoDeps,
} from './interpolationUndo';
import type { HistoryEntry } from '../../../types/annotation';

const EVENT_NAME = 'CS_TOOLS_ANNOTATION_INTERPOLATION_PROCESS_COMPLETED';

function makeEntry(label: string, opts: {
  applyMark?: () => void;
  invertMark?: () => void;
  scope?: string[];
} = {}): HistoryEntry {
  return {
    description: label,
    apply: opts.applyMark ?? (() => undefined),
    invert: opts.invertMark ?? (() => undefined),
    scopeMemberIds: opts.scope ?? [],
    at: 0,
  };
}

function makeDetail(segmentationId: string): unknown {
  return {
    annotation: { data: { segmentation: { segmentationId } } },
    element: {} as unknown,
    viewportId: 'vp1',
    renderingEngineId: 're1',
  };
}

afterEach(() => {
  dispose();
  resetInterpolationUndoWiring();
});

beforeEach(() => {
  resetInterpolationUndoWiring();
});

// ─── mergeEntries ─────────────────────────────────────────────────────

describe('mergeEntries', () => {
  it('applies in stack order (oldest-first), inverts in reverse (newest-first)', () => {
    const log: string[] = [];
    const entries = [
      makeEntry('a', { applyMark: () => log.push('apply-a'), invertMark: () => log.push('invert-a') }),
      makeEntry('b', { applyMark: () => log.push('apply-b'), invertMark: () => log.push('invert-b') }),
      makeEntry('c', { applyMark: () => log.push('apply-c'), invertMark: () => log.push('invert-c') }),
    ];
    const merged = mergeEntries(entries);
    merged.apply();
    expect(log).toEqual(['apply-a', 'apply-b', 'apply-c']);
    log.length = 0;
    merged.invert();
    expect(log).toEqual(['invert-c', 'invert-b', 'invert-a']);
  });

  it('produces a count-aware description for >1 entries', () => {
    const merged = mergeEntries([makeEntry('a'), makeEntry('b'), makeEntry('c')]);
    expect(merged.description).toBe('Interpolate 3 contours');
  });

  it('preserves the single entry’s description when only one is merged', () => {
    const merged = mergeEntries([makeEntry('only one')]);
    expect(merged.description).toBe('only one');
  });

  it('unions scopeMemberIds without duplicates', () => {
    const merged = mergeEntries([
      makeEntry('a', { scope: ['m1', 'm2'] }),
      makeEntry('b', { scope: ['m2', 'm3'] }),
      makeEntry('c', { scope: ['m3'] }),
    ]);
    expect(new Set(merged.scopeMemberIds)).toEqual(new Set(['m1', 'm2', 'm3']));
    expect(merged.scopeMemberIds.length).toBe(3);
  });

  it('apply / invert keep going past a thrown closure (warn + continue)', () => {
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined);
    const log: string[] = [];
    const entries = [
      makeEntry('a', { applyMark: () => log.push('a') }),
      makeEntry('b', { applyMark: () => { throw new Error('boom'); } }),
      makeEntry('c', { applyMark: () => log.push('c') }),
    ];
    mergeEntries(entries).apply();
    expect(log).toEqual(['a', 'c']);
    expect(warn).toHaveBeenCalled();
    warn.mockRestore();
  });
});

// ─── handleInterpolationCompleted (pure) ──────────────────────────────

interface Calls {
  resolveCalls: string[];
  takeCalls: string[];
  recordCalls: Array<[string, HistoryEntry]>;
}

function makeDeps(opts: {
  containerId?: (segId: string) => string | null;
  buffer?: Map<string, HistoryEntry[]>;
} = {}): { deps: InterpolationUndoDeps; calls: Calls } {
  const calls: Calls = { resolveCalls: [], takeCalls: [], recordCalls: [] };
  const buf = opts.buffer ?? new Map<string, HistoryEntry[]>();
  const deps: InterpolationUndoDeps = {
    getContainerId(segId) {
      calls.resolveCalls.push(segId);
      return opts.containerId
        ? opts.containerId(segId)
        : `container_${segId}`;
    },
    takeAutoGeneratedBuffer(containerId) {
      calls.takeCalls.push(containerId);
      const out = buf.get(containerId) ?? [];
      buf.delete(containerId);
      return out;
    },
    recordEntry(containerId, entry) {
      calls.recordCalls.push([containerId, entry]);
    },
  };
  return { deps, calls };
}

describe('handleInterpolationCompleted', () => {
  it('drains the buffer and records ONE merged entry (per design §B5)', () => {
    const buf = new Map<string, HistoryEntry[]>();
    buf.set('container_seg_1', [makeEntry('e1'), makeEntry('e2'), makeEntry('e3')]);
    const { deps, calls } = makeDeps({ buffer: buf });
    const n = handleInterpolationCompleted(makeDetail('seg_1'), deps);
    expect(n).toBe(3);
    expect(calls.recordCalls).toHaveLength(1);
    expect(calls.recordCalls[0][0]).toBe('container_seg_1');
    expect(calls.recordCalls[0][1].description).toBe('Interpolate 3 contours');
  });

  it('returns 0 and records nothing when the buffer is empty', () => {
    const { deps, calls } = makeDeps();
    const n = handleInterpolationCompleted(makeDetail('seg_1'), deps);
    expect(n).toBe(0);
    expect(calls.recordCalls).toEqual([]);
  });

  it('returns 0 when getContainerId resolves to null', () => {
    const buf = new Map<string, HistoryEntry[]>();
    buf.set('container_seg_1', [makeEntry('e1')]);
    const { deps, calls } = makeDeps({
      buffer: buf,
      containerId: () => null,
    });
    const n = handleInterpolationCompleted(makeDetail('seg_1'), deps);
    expect(n).toBe(0);
    expect(calls.takeCalls).toEqual([]);
    expect(calls.recordCalls).toEqual([]);
  });

  it('skips on malformed details (no throw)', () => {
    const { deps, calls } = makeDeps();
    expect(() => handleInterpolationCompleted(undefined, deps)).not.toThrow();
    expect(() => handleInterpolationCompleted({}, deps)).not.toThrow();
    expect(() => handleInterpolationCompleted({ annotation: 'x' }, deps)).not.toThrow();
    expect(calls.recordCalls).toEqual([]);
  });
});

// ─── Lifecycle ────────────────────────────────────────────────────────

describe('initialize / dispose lifecycle', () => {
  it('subscribes to the completion event on initialize()', () => {
    const buf = new Map<string, HistoryEntry[]>();
    buf.set('container_seg_1', [makeEntry('e1')]);
    const { deps, calls } = makeDeps({ buffer: buf });
    wireInterpolationUndo(deps);
    initialize();
    mockEventTarget.dispatchEvent(
      new CustomEvent(EVENT_NAME, { detail: makeDetail('seg_1') }),
    );
    expect(calls.recordCalls).toHaveLength(1);
  });

  it('idempotent on a second initialize() — does not double-subscribe', () => {
    const buf = new Map<string, HistoryEntry[]>();
    buf.set('container_seg_1', [makeEntry('e1')]);
    const { deps, calls } = makeDeps({ buffer: buf });
    wireInterpolationUndo(deps);
    initialize();
    initialize();
    mockEventTarget.dispatchEvent(
      new CustomEvent(EVENT_NAME, { detail: makeDetail('seg_1') }),
    );
    expect(calls.recordCalls).toHaveLength(1);
  });

  it('dispose() detaches the listener', () => {
    const buf = new Map<string, HistoryEntry[]>();
    buf.set('container_seg_1', [makeEntry('e1')]);
    const { deps, calls } = makeDeps({ buffer: buf });
    wireInterpolationUndo(deps);
    initialize();
    dispose();
    mockEventTarget.dispatchEvent(
      new CustomEvent(EVENT_NAME, { detail: makeDetail('seg_1') }),
    );
    expect(calls.recordCalls).toEqual([]);
  });

  it('dispose() before initialize() is safe', () => {
    expect(() => dispose()).not.toThrow();
  });

  it('a throw inside the deps surfaces as a console warning, not a dispatcher break', () => {
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined);
    wireInterpolationUndo({
      getContainerId: () => { throw new Error('boom'); },
      takeAutoGeneratedBuffer: () => [],
      recordEntry: () => undefined,
    });
    initialize();
    expect(() =>
      mockEventTarget.dispatchEvent(
        new CustomEvent(EVENT_NAME, { detail: makeDetail('seg_1') }),
      ),
    ).not.toThrow();
    expect(warn).toHaveBeenCalled();
    warn.mockRestore();
  });
});
