/**
 * Provenance stamping on inter-slice interpolation completion.
 *
 * MV-Phase 4.1. When Cornerstone fires
 * `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED` (after `interpolate()`
 * generates contours for a gap), this module:
 *
 *   1. Reads the source-annotation's `(segmentationId, segmentIndex)` from
 *      the event detail.
 *   2. Resolves to a Member via the container bridge.
 *   3. Stamps `provenance: 'interpolated'` and
 *      `interpolationState: 'has-interpolated'` on that member.
 *
 * The event fires once per interpolation pair. Stamping is idempotent at
 * the containerService setter level (no-op when the value is unchanged),
 * so duplicate stamps across multiple pairs in a single op are harmless.
 *
 * Per design §B5 the stamp is the metadata behind the "auto" marker that
 * fades on manual edit (Phase 4.4) or save (Phase 4.5). Per §D7.10 the
 * stamp itself is session-only and does NOT mark the container dirty —
 * the geometry creation that prompted the interpolation already runs
 * through the standard contour-add dirty pipeline.
 *
 * DI pattern matches `styling.ts` / `memberVisibility.ts` so tests pass
 * synthetic deps without module-level Cornerstone mocks. Production
 * wires the real Cornerstone event surface and containerService dispatch
 * via `wireProvenance` from `segmentationService.initialize()`.
 *
 * Ordering note: this handler reads the event detail (not the global
 * annotation state filtered on `autoGenerated`), so it is robust against
 * `autoAcceptInterpolated.ts` flipping the source annotation's
 * `autoGenerated` flag in the same event-dispatch pass. Initialize order
 * in `segmentationService.initialize()` is left tolerant to either
 * ordering.
 */
import { eventTarget } from '@cornerstonejs/core';
import { Enums as ToolEnums } from '@cornerstonejs/tools';

// ─── DI seam ──────────────────────────────────────────────────────────

export interface ProvenanceDeps {
  /**
   * Resolve a (csSegmentationId, segmentIndex) pair to a memberId.
   * Returns null when the segmentation isn't tracked by the container
   * bridge (e.g., the segmentation was created and deleted before the
   * interpolation event drained, or the bridge isn't initialized).
   */
  memberIdForCsSegment: (
    csSegmentationId: string,
    segmentIndex: number,
  ) => string | null;

  /**
   * Stamp the member as interpolation-derived. Implementations call
   * `containerService.setMemberProvenance(memberId, 'interpolated')` and
   * `setMemberInterpolationState(memberId, 'has-interpolated')` in the
   * production path.
   */
  stampInterpolated: (memberId: string) => void;

  /**
   * Phase 4.4: clear the interpolated marker on a member after a manual
   * edit. Production implementation reads the current provenance from
   * the bridge and conditionally flips `'interpolated'` → `'manual'`,
   * always clearing `interpolationState` to `'none'`. Idempotent on
   * already-cleared members.
   */
  clearInterpolatedMark: (memberId: string) => void;
}

// ─── Pure handler ─────────────────────────────────────────────────────

/**
 * Process one `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED` event detail.
 * Pure — takes the event detail shape and the deps, returns void.
 *
 * Resolution rule:
 *   - `detail.annotation.data.segmentation.{segmentationId, segmentIndex}`
 *     names the segment that was just interpolated.
 *   - We resolve that pair to a memberId via the bridge.
 *   - If the resolution succeeds, we stamp the member.
 *
 * Anything malformed in the detail (missing fields, wrong types) is
 * silently ignored — the event is best-effort metadata; we never want
 * to throw on an unexpected detail shape.
 */
export function handleInterpolationCompleted(
  detail: unknown,
  deps: ProvenanceDeps,
): void {
  const segId = readSegmentationId(detail);
  const segIndex = readSegmentIndex(detail);
  if (typeof segId !== 'string' || segId.length === 0) return;
  if (!Number.isInteger(segIndex) || segIndex! <= 0) return;

  const memberId = deps.memberIdForCsSegment(segId, segIndex!);
  if (!memberId) return;
  deps.stampInterpolated(memberId);
}

function readSegmentationId(detail: unknown): string | undefined {
  const segmentation = readSegmentation(detail);
  return typeof segmentation?.segmentationId === 'string'
    ? segmentation.segmentationId
    : undefined;
}

function readSegmentIndex(detail: unknown): number | undefined {
  const segmentation = readSegmentation(detail);
  return typeof segmentation?.segmentIndex === 'number'
    ? segmentation.segmentIndex
    : undefined;
}

function readSegmentation(detail: unknown):
  | { segmentationId?: string; segmentIndex?: number }
  | undefined {
  const annotation = (detail as { annotation?: unknown } | undefined)?.annotation;
  const data = (annotation as { data?: unknown } | undefined)?.data;
  return (data as { segmentation?: { segmentationId?: string; segmentIndex?: number } } | undefined)
    ?.segmentation;
}

/**
 * Process one `ANNOTATION_MODIFIED` event detail. Per design §B5:
 * "Editing a handle on an interpolated contour mutates it like any
 * manual contour and clears its 'interpolated' mark."
 *
 * Filter rule:
 *   - Skip when `annotation.autoGenerated === true`. Mid-interpolation
 *     mutations on freshly-generated contours fire MODIFIED before
 *     `autoAcceptInterpolated` flips the flag; we don't want those to
 *     clear the marker we just stamped.
 *   - Skip on malformed details (no throw).
 *
 * The dep `clearInterpolatedMark` is responsible for the conditional
 * read-and-clear; the handler invokes it unconditionally for the
 * resolved member.
 */
export function handleAnnotationModified(
  detail: unknown,
  deps: ProvenanceDeps,
): void {
  if (readAutoGenerated(detail) === true) return;
  const segId = readSegmentationId(detail);
  const segIndex = readSegmentIndex(detail);
  if (typeof segId !== 'string' || segId.length === 0) return;
  if (!Number.isInteger(segIndex) || segIndex! <= 0) return;

  const memberId = deps.memberIdForCsSegment(segId, segIndex!);
  if (!memberId) return;
  deps.clearInterpolatedMark(memberId);
}

function readAutoGenerated(detail: unknown): boolean | undefined {
  const annotation = (detail as { annotation?: unknown } | undefined)?.annotation;
  const flag = (annotation as { autoGenerated?: boolean } | undefined)?.autoGenerated;
  return typeof flag === 'boolean' ? flag : undefined;
}

// ─── Listener lifecycle ───────────────────────────────────────────────
//
// Module-level state, a single `initialize()` that subscribes to
// Cornerstone's interpolation event, and a `dispose()` that detaches
// the listener. Tests skip the lifecycle entirely and invoke
// `handleInterpolationCompleted` directly.

const NOOP_DEPS: ProvenanceDeps = {
  memberIdForCsSegment: () => null,
  stampInterpolated: () => undefined,
  clearInterpolatedMark: () => undefined,
};

let deps: ProvenanceDeps = NOOP_DEPS;
let initialized = false;
let onInterpolationCompleted: EventListener | null = null;
let onAnnotationModified: EventListener | null = null;

/** Inject the production deps. Called from `segmentationService.initialize()`. */
export function wireProvenance(injected: Partial<ProvenanceDeps>): void {
  deps = { ...NOOP_DEPS, ...injected };
}

/** Reset the deps to no-op stubs. Used by test teardown. */
export function resetProvenanceWiring(): void {
  deps = NOOP_DEPS;
}

/**
 * Subscribe to `ANNOTATION_INTERPOLATION_PROCESS_COMPLETED` (Phase 4.1
 * stamping path) and `ANNOTATION_MODIFIED` (Phase 4.4 clear-on-edit
 * path). Idempotent — a second initialize() call is a no-op.
 * Cornerstone fires both events on `eventTarget`; we only need the
 * global subscription.
 */
export function initialize(): void {
  if (initialized) return;

  onInterpolationCompleted = (evt: Event) => {
    const detail = (evt as CustomEvent<unknown>).detail;
    try {
      handleInterpolationCompleted(detail, deps);
    } catch (err) {
      // Stamping is metadata — never surface a throw to Cornerstone's
      // dispatcher. The render-dispatch-throws-break-interpolation memory
      // applies here: the source annotation has already been written to
      // global state, so killing the dispatcher would leave us in a
      // worse state than just losing the stamp on this pass.
      console.warn('[provenance] stamp failed', err);
    }
  };

  onAnnotationModified = (evt: Event) => {
    const detail = (evt as CustomEvent<unknown>).detail;
    try {
      handleAnnotationModified(detail, deps);
    } catch (err) {
      // Same dispatcher-protection rationale.
      console.warn('[provenance] clear-on-edit failed', err);
    }
  };

  const interpolationEvent = (ToolEnums.Events as Record<string, string>)
    .ANNOTATION_INTERPOLATION_PROCESS_COMPLETED;
  if (interpolationEvent) {
    eventTarget.addEventListener(interpolationEvent, onInterpolationCompleted);
  }

  const modifiedEvent = (ToolEnums.Events as Record<string, string>)
    .ANNOTATION_MODIFIED;
  if (modifiedEvent) {
    eventTarget.addEventListener(modifiedEvent, onAnnotationModified);
  }

  initialized = true;
}

/** Tear down the listeners. Idempotent. */
export function dispose(): void {
  if (!initialized) return;
  const interpolationEvent = (ToolEnums.Events as Record<string, string>)
    .ANNOTATION_INTERPOLATION_PROCESS_COMPLETED;
  if (interpolationEvent && onInterpolationCompleted) {
    eventTarget.removeEventListener(interpolationEvent, onInterpolationCompleted);
  }
  const modifiedEvent = (ToolEnums.Events as Record<string, string>)
    .ANNOTATION_MODIFIED;
  if (modifiedEvent && onAnnotationModified) {
    eventTarget.removeEventListener(modifiedEvent, onAnnotationModified);
  }
  onInterpolationCompleted = null;
  onAnnotationModified = null;
  initialized = false;
}
