/**
 * Segmentations E2E Tests
 *
 * Tests creating segmentations, painting with brush, and toggling visibility.
 *
 * The segmentation panel ("Annotate") contains annotation rows. After creating
 * a segmentation and selecting its row, the tool grid (Brush, Eraser, etc.)
 * becomes available.
 */
import { test, expect } from '../fixtures/auth';
import type { Page } from '@playwright/test';
import { XnatBrowserPage } from '../pages/xnat-browser.page';
import { ViewerPage } from '../pages/viewer.page';
import { getE2EConfig, type E2EConfig } from '../helpers/env';

let config: E2EConfig;

async function getActiveSegmentationState(page: Page) {
  return page.evaluate(() => {
    return (window as any).__XNAT_E2E__?.getActiveSegmentationState?.() ?? {
      activeSegmentationId: null,
      activeSegmentIndex: 0,
    };
  });
}

async function getActiveContourSnapshot(
  page: Page,
  panelId = 'panel_0',
  segmentationId?: string | null,
) {
  return page.evaluate(({ currentPanelId, currentSegmentationId }: { currentPanelId: string; currentSegmentationId?: string | null }) => {
    return (window as any).__XNAT_E2E__?.getActiveContourSnapshot?.(currentPanelId, currentSegmentationId) ?? {
      activeSegmentationId: null,
      activeSegmentIndex: 0,
      currentImageId: null,
      currentSliceIndex: null,
      total: 0,
      onCurrentSlice: 0,
      autoGeneratedTotal: 0,
      autoGeneratedOnCurrentSlice: 0,
      sliceIndices: [],
      autoGeneratedSliceIndices: [],
      selected: [],
    };
  }, { currentPanelId: panelId, currentSegmentationId: segmentationId });
}

async function setSegmentLocked(page: Page, segmentationId: string, segmentIndex: number, locked: boolean) {
  await page.evaluate(({ currentSegmentationId, currentSegmentIndex, currentLocked }) => {
    (window as any).__XNAT_E2E__?.setSegmentLocked?.(currentSegmentationId, currentSegmentIndex, currentLocked);
  }, {
    currentSegmentationId: segmentationId,
    currentSegmentIndex: segmentIndex,
    currentLocked: locked,
  });
}

async function getLockAwareUndoRedoCounter(page: Page): Promise<number> {
  return page.evaluate(() => {
    return (window as any).__XNAT_E2E__?.getLockAwareUndoRedoCounter?.() ?? -1;
  });
}

async function getCurrentImageNumber(viewer: ViewerPage): Promise<number | null> {
  const text = await viewer.getImageIndexText();
  const match = text.match(/(\d+)\s*\/\s*(\d+)/);
  return match ? Number(match[1]) : null;
}

test.describe('Segmentations', () => {
  test.beforeAll(() => { config = getE2EConfig(); });

  // Load an image before each test
  test.beforeEach(async ({ authenticatedPage: page }) => {
    const browser = new XnatBrowserPage(page);
    const level = await browser.currentLevel();
    if (level !== 'projects') {
      await browser.navigateToProjects();
    }
    await browser.navigateAndLoadScan(
      config.testProject, config.testSubject, config.testSession, config.testScan,
    );
    const viewer = new ViewerPage(page);
    await viewer.waitForImageLoaded();

    // Dismiss any leftover dialogs/overlays from previous tests
    await page.keyboard.press('Escape');
    await page.waitForTimeout(200);

    // If an "unsaved annotations" dialog appeared during navigation, dismiss it
    const unsavedDialog = page.locator('button', { hasText: 'Continue without saving' });
    if (await unsavedDialog.isVisible({ timeout: 500 }).catch(() => false)) {
      await unsavedDialog.click();
      await page.waitForTimeout(500);
    }

    // Ensure the segmentation panel is open
    await viewer.openSegmentationPanel();
  });

  test('create new segmentation', async ({ authenticatedPage: page }) => {
    const segPanel = page.locator('[data-testid="segmentation-panel"]');

    // Click "Add segmentation" button
    await page.locator('[data-testid="add-segmentation-btn"]').click();
    await page.waitForTimeout(500);

    // Name entry dialog should appear — fill name and confirm
    const nameInput = segPanel.locator('input.bg-zinc-800');
    await expect(nameInput).toBeVisible({ timeout: 3_000 });
    await nameInput.fill('E2E Test Seg');

    const createBtn = page.locator('button', { hasText: 'Create' });
    await createBtn.click();
    await page.waitForTimeout(1000);

    // A new annotation row should appear in the panel
    // The panel should now show at least one entry
    const rows = segPanel.locator('.cursor-pointer, [role="button"]');
    const count = await rows.count();
    expect(count).toBeGreaterThanOrEqual(1);
  });

  test('brush painting works on viewport', async ({ authenticatedPage: page }) => {
    const viewer = new ViewerPage(page);
    const segPanel = page.locator('[data-testid="segmentation-panel"]');

    // Create a new segmentation
    await page.locator('[data-testid="add-segmentation-btn"]').click();
    await page.waitForTimeout(500);

    const nameInput = segPanel.locator('input.bg-zinc-800');
    await expect(nameInput).toBeVisible({ timeout: 3_000 });
    await nameInput.fill('Brush Test');
    await page.locator('button', { hasText: 'Create' }).click();
    await page.waitForTimeout(1000);

    // Select the annotation row to enable tools.
    // The first clickable row in the panel list that contains "Brush Test" or a segment entry.
    const annotationRow = segPanel.locator('.cursor-pointer').first();
    await annotationRow.click();
    await page.waitForTimeout(500);

    // Now the tools grid should be visible — click "Brush"
    const brushBtn = segPanel.locator('button', { hasText: 'Brush' }).first();
    if (await brushBtn.isVisible({ timeout: 3_000 }).catch(() => false)) {
      await brushBtn.click();
      await page.waitForTimeout(300);

      // Paint a stroke on the viewport
      await viewer.canvas.paintStroke([
        { x: 0.4, y: 0.4 },
        { x: 0.45, y: 0.42 },
        { x: 0.5, y: 0.45 },
        { x: 0.55, y: 0.47 },
        { x: 0.6, y: 0.5 },
      ]);
      await page.waitForTimeout(500);
    }

    // Verify no error on viewport
    await expect(viewer.viewportError).toBeHidden();
  });

  test('toggle segment visibility', async ({ authenticatedPage: page }) => {
    const segPanel = page.locator('[data-testid="segmentation-panel"]');

    // Create a new segmentation
    await page.locator('[data-testid="add-segmentation-btn"]').click();
    await page.waitForTimeout(500);

    const nameInput = segPanel.locator('input.bg-zinc-800');
    await expect(nameInput).toBeVisible({ timeout: 3_000 });
    await nameInput.fill('Visibility Test');
    await page.locator('button', { hasText: 'Create' }).click();
    await page.waitForTimeout(1000);

    // Find the visibility toggle button ("Hide segment" / "Show segment")
    const hideBtn = segPanel.locator('button[title="Hide segment"]').first();

    if (await hideBtn.isVisible({ timeout: 3_000 }).catch(() => false)) {
      // Click to hide
      await hideBtn.click();
      await page.waitForTimeout(300);

      // Should now show "Show segment" button
      const showBtn = segPanel.locator('button[title="Show segment"]').first();
      await expect(showBtn).toBeVisible({ timeout: 3_000 });

      // Click to show again
      await showBtn.click();
      await page.waitForTimeout(300);

      // Should be back to "Hide segment"
      await expect(hideBtn).toBeVisible({ timeout: 3_000 });
    }
  });

  test('does not allow editing a locked annotation after switching from an editable annotation', async ({ authenticatedPage: page }) => {
    const segPanel = page.locator('[data-testid="segmentation-panel"]');

    const createSegmentationWithSegment = async (name: string) => {
      const addSegmentButtons = segPanel.getByRole('button', { name: 'Add Segment', exact: true });
      const priorAddSegmentCount = await addSegmentButtons.count();
      const lockButtons = segPanel.locator('button[title="Lock segment"]');
      const priorLockCount = await lockButtons.count();

      await page.locator('[data-testid="add-segmentation-btn"]').click();
      const nameInput = page.getByPlaceholder('Enter segmentation name...');
      await expect(nameInput).toBeVisible({ timeout: 3_000 });
      await nameInput.fill(name);
      await page.getByRole('button', { name: 'Create' }).click();
      await expect(nameInput).toBeHidden({ timeout: 5_000 });
      await expect(addSegmentButtons).toHaveCount(priorAddSegmentCount + 1, { timeout: 5_000 });

      const addSegmentButton = addSegmentButtons.last();
      await expect(addSegmentButton).toBeVisible({ timeout: 3_000 });
      await addSegmentButton.click();

      await expect(page.getByText('Segment name')).toBeVisible({ timeout: 3_000 });
      await page.getByRole('button', { name: 'Add', exact: true }).click();
      await expect(lockButtons).toHaveCount(priorLockCount + 1, { timeout: 5_000 });
    };

    await createSegmentationWithSegment('Editable Seg');
    await createSegmentationWithSegment('Locked Seg');

    const lockButton = segPanel.locator('button[title="Lock segment"]').last();
    await expect(lockButton).toBeVisible({ timeout: 3_000 });
    await lockButton.click();

    const editableSegmentRow = segPanel
      .locator('button[title="Lock segment"]')
      .first()
      .locator('xpath=ancestor::div[contains(@class, "cursor-pointer")][1]');
    await editableSegmentRow.click();
    const brushButton = segPanel.locator('button', { hasText: 'Brush' }).first();
    await expect(brushButton).toBeEnabled({ timeout: 3_000 });
    await brushButton.click();

    const lockedSegmentRow = segPanel
      .locator('button[title="Unlock segment"]')
      .first()
      .locator('xpath=ancestor::div[contains(@class, "cursor-pointer")][1]');
    await lockedSegmentRow.click();

    await expect(brushButton).toBeDisabled({ timeout: 3_000 });
    await expect(segPanel.getByText(/unlock segment to edit/i)).toBeVisible({ timeout: 3_000 });
  });

  test('blocks undo and redo for locked copied contours until the annotation is unlocked', async ({ authenticatedPage: page }) => {
    const structureLabel = 'Locked History Structure';

    await expect.poll(async () => {
      return page.evaluate(() => ({
        hasHook: Boolean((window as any).__XNAT_E2E__),
        hasSetSegmentLocked: Boolean((window as any).__XNAT_E2E__?.setSegmentLocked),
        hasHistoryMemoFactory: Boolean((window as any).__XNAT_E2E__?.createLockAwareUndoRedoTestMemo),
        hasHistoryCounter: Boolean((window as any).__XNAT_E2E__?.getLockAwareUndoRedoCounter),
      }));
    }, { timeout: 10_000 }).toEqual({
      hasHook: true,
      hasSetSegmentLocked: true,
      hasHistoryMemoFactory: true,
      hasHistoryCounter: true,
    });

    const segmentationId = await page.evaluate(async (label: string) => {
      return (window as any).__XNAT_E2E__?.createTestStructure?.('panel_0', label) ?? null;
    }, structureLabel);
    expect(segmentationId).toBeTruthy();

    expect(await page.evaluate((currentSegmentationId: string) => {
      return (window as any).__XNAT_E2E__?.createLockAwareUndoRedoTestMemo?.(currentSegmentationId, 1) ?? false;
    }, segmentationId)).toBe(true);
    expect(await getLockAwareUndoRedoCounter(page)).toBe(0);

    await setSegmentLocked(page, segmentationId, 1, true);
    await page.keyboard.press('Control+Z');

    await expect(page.getByRole('heading', { name: 'Undo blocked' })).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText(`Unlock ${structureLabel} Segment before applying undo.`)).toBeVisible({ timeout: 10_000 });
    await page.getByRole('button', { name: 'OK' }).click();

    await expect.poll(async () => getLockAwareUndoRedoCounter(page), { timeout: 10_000 }).toBe(0);

    await setSegmentLocked(page, segmentationId, 1, false);
    await page.keyboard.press('Control+Z');
    await expect.poll(async () => getLockAwareUndoRedoCounter(page), { timeout: 10_000 }).toBe(1);

    await setSegmentLocked(page, segmentationId, 1, true);
    await page.keyboard.press('Control+Shift+Z');

    await expect(page.getByRole('heading', { name: 'Redo blocked' })).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText('Unlock the locked annotations before applying redo:')).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText(`- ${structureLabel} Segment`)).toBeVisible({ timeout: 10_000 });
    await page.getByRole('button', { name: 'OK' }).click();

    await expect.poll(async () => getLockAwareUndoRedoCounter(page), { timeout: 10_000 }).toBe(1);

    await setSegmentLocked(page, segmentationId, 1, false);
    await page.keyboard.press('Control+Shift+Z');
    await expect.poll(async () => getLockAwareUndoRedoCounter(page), { timeout: 10_000 }).toBe(2);
  });

  test('clicking a contour in the viewport activates it and ctrl-c/ctrl-v pastes it onto another slice with undo/redo and interpolation', async ({ authenticatedPage: page }) => {
    const viewer = new ViewerPage(page);

    await expect.poll(async () => {
      return page.evaluate(() => ({
        hasHook: Boolean((window as any).__XNAT_E2E__),
        hasCreateTestStructure: Boolean((window as any).__XNAT_E2E__?.createTestStructure),
      }));
    }, { timeout: 10_000 }).toEqual({
      hasHook: true,
      hasCreateTestStructure: true,
    });

    const structureAId = await page.evaluate(async () => {
      return (window as any).__XNAT_E2E__?.createTestStructure?.('panel_0', 'Viewport Structure A') ?? null;
    });
    const structureBId = await page.evaluate(async () => {
      return (window as any).__XNAT_E2E__?.createTestStructure?.('panel_0', 'Viewport Structure B') ?? null;
    });
    expect(structureAId).toBeTruthy();
    expect(structureBId).toBeTruthy();

    await page.evaluate((segmentationId: string) => {
      (window as any).__XNAT_E2E__?.activateSegmentation?.('panel_0', segmentationId, 1);
    }, structureAId);
    await expect.poll(async () => (await getActiveSegmentationState(page)).activeSegmentationId).toBe(structureAId);

    const contourAnnotationId = await page.evaluate((segmentationId: string) => {
      return (window as any).__XNAT_E2E__?.createTestContour?.('panel_0', segmentationId, 1) ?? null;
    }, structureAId);
    expect(contourAnnotationId).toBeTruthy();

    await expect
      .poll(async () => (await getActiveContourSnapshot(page, 'panel_0', structureAId)).total, { timeout: 10_000 })
      .toBeGreaterThanOrEqual(1);

    await page.evaluate((segmentationId: string) => {
      (window as any).__XNAT_E2E__?.activateSegmentation?.('panel_0', segmentationId, 1);
    }, structureBId);
    await expect.poll(async () => (await getActiveSegmentationState(page)).activeSegmentationId).toBe(structureBId);

    await page.evaluate(() => {
      (window as any).__XNAT_E2E__?.setSelectionTool?.();
    });
    await viewer.canvas.click({ x: 0.38, y: 0.38 });
    await expect.poll(async () => (await getActiveContourSnapshot(page, 'panel_0', structureAId)).selected.length).toBeGreaterThanOrEqual(1);

    const sourceSnapshot = await getActiveContourSnapshot(page, 'panel_0', structureAId);
    expect(sourceSnapshot.total).toBeGreaterThanOrEqual(1);
    expect(sourceSnapshot.onCurrentSlice).toBeGreaterThanOrEqual(1);
    expect(sourceSnapshot.selected.length).toBeGreaterThanOrEqual(1);
    const sourceImageNumber = await getCurrentImageNumber(viewer);
    expect(sourceImageNumber).not.toBeNull();

    await page.keyboard.press('Control+C');
    for (let i = 0; i < 6; i++) {
      await viewer.canvas.scroll(900);
      const currentImageNumber = await getCurrentImageNumber(viewer);
      if (
        currentImageNumber != null
        && sourceImageNumber != null
        && currentImageNumber >= sourceImageNumber + 3
      ) {
        break;
      }
    }

    await expect
      .poll(async () => getCurrentImageNumber(viewer), { timeout: 10_000 })
      .toBeGreaterThanOrEqual((sourceImageNumber ?? 0) + 3);

    const beforePasteSnapshot = await getActiveContourSnapshot(page, 'panel_0', structureAId);
    expect(beforePasteSnapshot.onCurrentSlice).toBe(0);
    expect(beforePasteSnapshot.autoGeneratedTotal).toBe(0);
    const targetImageNumber = await getCurrentImageNumber(viewer);
    expect(targetImageNumber).not.toBeNull();
    const interpolationCount = Math.max(0, (targetImageNumber ?? 0) - (sourceImageNumber ?? 0) - 1);

    await page.keyboard.press('Control+V');

    await expect.poll(async () => {
      const snapshot = await getActiveContourSnapshot(page, 'panel_0', structureAId);
      return {
        total: snapshot.total,
        onCurrentSlice: snapshot.onCurrentSlice,
        selectedCount: snapshot.selected.length,
        autoGeneratedTotal: snapshot.autoGeneratedTotal,
      };
    }, { timeout: 10_000 }).toEqual({
      total: sourceSnapshot.total + 1 + interpolationCount,
      onCurrentSlice: 1,
      selectedCount: 1,
      autoGeneratedTotal: interpolationCount,
    });

    const afterPasteSnapshot = await getActiveContourSnapshot(page, 'panel_0', structureAId);
    expect(afterPasteSnapshot.autoGeneratedTotal).toBe(interpolationCount);

    await page.keyboard.press('Control+Z');

    await expect.poll(async () => {
      const snapshot = await getActiveContourSnapshot(page, 'panel_0', structureAId);
      return {
        total: snapshot.total,
        onCurrentSlice: snapshot.onCurrentSlice,
        autoGeneratedTotal: snapshot.autoGeneratedTotal,
      };
    }, { timeout: 10_000 }).toEqual({
      total: sourceSnapshot.total,
      onCurrentSlice: 0,
      autoGeneratedTotal: 0,
    });

    await page.keyboard.press('Control+Shift+Z');

    await expect.poll(async () => {
      const snapshot = await getActiveContourSnapshot(page, 'panel_0', structureAId);
      return {
        total: snapshot.total,
        onCurrentSlice: snapshot.onCurrentSlice,
        autoGeneratedTotal: snapshot.autoGeneratedTotal,
      };
    }, { timeout: 10_000 }).toEqual({
      total: sourceSnapshot.total + 1 + interpolationCount,
      onCurrentSlice: 1,
      autoGeneratedTotal: interpolationCount,
    });
  });
});
