/**
 * Phase 4 — signal 22 (interpolation provenance): an interpolated contour shows the
 * `interpolated` (auto) badge on its member row in the Annotations panel.
 *
 * Write-through (B5) accepts interpolated contours the instant they're generated,
 * clearing Cornerstone's transient `autoGenerated` flag — so the panel can't recover
 * "was interpolated" from it. Provenance is therefore stamped PERSISTENTLY at
 * interpolation time (interpolationAcceptance.acceptAnnotation → metadata.provenance =
 * 'interpolated'); the panel reads it back (segmentProvenance) and lights the badge
 * MemberRow already renders for `provenance === 'interpolated'`.
 *
 * Faithful real-path test: a structure container + a contour stamped with the SAME
 * provenance interpolation produces, driven through the REAL panel render (open the
 * panel from the toolbar, read the rendered member row) — no badge setter shortcut.
 * RED before the panel supplies `provenanceOf`; GREEN once it's wired through.
 */
import { test, expect } from '../fixtures/electron-app';
import type { Page } from '@playwright/test';
import { loadFixture } from '../helpers/local-fixture';

interface E2EHooks {
  resetUnifiedSegmentations: () => void;
  createTestStructure: (panelId: string, label: string) => Promise<string>;
  createTestContour: (panelId: string, segmentationId: string, segmentIndex?: number, provenance?: string) => string | null;
}
type Win = { __XNAT_E2E__: E2EHooks };

/** Open the panel if it isn't already open (the toolbar toggle's label flips, and a
 *  prior spec in the shared worker app may have left it open). */
async function ensurePanelOpen(page: Page) {
  const panel = page.locator('[data-testid="annotations-side-panel"]');
  if (await panel.isVisible()) return;
  await page.getByRole('button', { name: 'Show segmentation panel' }).click();
}

test('an interpolated contour shows the "auto" provenance badge on its member row (signal 22)', async ({ page }) => {
  await loadFixture(page, 'ct-axial-300', 'panel_0');
  // Isolate from any container a prior spec left in the worker-scoped app.
  await page.evaluate(() => (window as unknown as Win).__XNAT_E2E__.resetUnifiedSegmentations());

  // Create a structure container with one member, then give that member a contour
  // stamped with the provenance interpolation produces ('interpolated').
  const segId = await page.evaluate(
    () => (window as unknown as Win).__XNAT_E2E__.createTestStructure('panel_0', 'GTV'),
  );
  const uid = await page.evaluate(
    (id) => (window as unknown as Win).__XNAT_E2E__.createTestContour('panel_0', id, 1, 'interpolated'),
    segId,
  );
  expect(uid).toBeTruthy();

  // Open the real panel; the member row for the interpolated contour shows the "auto" badge.
  await ensurePanelOpen(page);
  const panel = page.locator('[data-testid="annotations-side-panel"]');
  await expect(panel).toBeVisible({ timeout: 15_000 });
  await expect(panel.getByText('auto', { exact: true })).toBeVisible({ timeout: 10_000 });
});
